### ISSUE TITLE
Chatterino won't load messages sent before the connection

### ISSUE THREAD

**Issue by cxcvb0** [fourtf/chatterino2#1006]
I can't see messages sent before I connected to the chat.
It doesn't work on Chatterino 1 as well.
I tried reinstalling both, nothing helps.
![Screenshot_78](https://user-images.githubusercontent.com/29178135/55958888-f304a480-5c69-11e9-821d-f96395c55549.png)

**Comment by Ckath** [comment]
this is due to changes in the twitch api, currently the `pajlada-dev` branch is patched with this functionality from RAnders00's api. Honestly not entirely sure if there's builds floating around of that, but if you have the means compiling from that branch will fix it.

**Comment by RAnders00** [comment]
The latest nightly has this functionality back

**Comment by pajlada** [comment]
Fixed in the Nightly build available under Releases
