### ISSUE TITLE
Delete message support

### ISSUE THREAD

**Issue by notheowner** [fourtf/chatterino2#1009]
![chrome_0vBMc6Q7R6](https://user-images.githubusercontent.com/25968992/56165144-1d3bc680-5fca-11e9-9f03-71cccf28dc1a.png)
In normal twitch chat, there is a moderator option that deletes the specific message instead of timing out the user entirely and all the message history.
Currently Chatterino 2 doesn't even show if a message gets deleted. Related to #955 

The button could be added next to name of chatter when you enable the mod icons.

**Comment by pajlada** [comment]
Fixed in latest nightly by @apa420 in PR #1012 
Icon made by me 
![image](https://user-images.githubusercontent.com/962989/57041230-018b1e00-6c62-11e9-9459-08b0ae5cde24.png)
