### ISSUE TITLE
Subscriber badge for Twitch Affiliate channel doesn't show up

### ISSUE THREAD

**Issue by Confuseh** [fourtf/chatterino2#102]
Whenever subscriber talks in twitch affiliate channel no badge shows up along with this in stdout:

    No channel badge set with key `subscriber`. Exception:  map::at
Perhaps it could be replaced with this:
![Twitch Affiliate subscriber badge](https://static-cdn.jtvnw.net/badges/v1/5d9f2208-5dd8-11e7-8513-2ff4adfae661/1) xd: ![KKool](https://cdn.betterttv.net/emote/56c2cff2d9ec6bf744247bf1/1x)

**Comment by pajlada** [comment]
Fixed in ad8ee97de98c5af2c91c7329c2c9ae9c72d6e48d
