### ISSUE TITLE
invisible character code issue

### ISSUE THREAD

**Issue by hemirt** [fourtf/chatterino2#1024]
https://github.com/fourtf/chatterino2/commit/40b4c2fefc6d3a4541f784a1e6bbefffc828a156
this shouldnt be a plain character, but an encoded sequence, imo

**Comment by hemirt** [comment]
#1025 imo just use normal encoded bytes as in either normal const char * without any QChar and with \u encodes, or the messageSuffix is a QByteArray so find a way to write those bytes into it [](https://static-cdn.jtvnw.net/emoticons/v1/1496047/2.0)

**Comment by semoog** [comment]
Is this related to the invisible character no longer working at all for sending duplicate messages? Don't see an issue about it - but have heard others say the same.

**Comment by hemirt** [comment]
the character that chatterino was using in earlier version, got ![](https://static-cdn.jtvnw.net/emoticons/v1/1496047/2.0) ed away by twitch, and no longer works for sending duplicate messages, there was a new character added into newer version which works, but there is a programming issue, not a behaviour issue, that is, that the character is written as an unicode character in the source code, instead of a unicode character escape sequence (aka for example illustrated on space character is written plainly as space " " instead of its escape sequence "\x2F" (obviously works fine for plain ascii characters and the normal unicode set, but the extended unicodes could have problems on machines with no support for them (again only in programming), not using)
