### ISSUE TITLE
Can not build on Ubuntu

### ISSUE THREAD

**Issue by Heermod** [fourtf/chatterino2#1029]
chatterino2/src/PrecompiledHeader.hpp:3: error: irccommand.h: No such file or directory
 #    include <irccommand.h>
              ^~~~~~~~~~~~~~
Where do I get this file

**Comment by pajlada** [comment]
Make sure you cloned the project either like this:
`git clone https://github.com/fourtf/chatterino2 --recursive`
or that you ran `git submodule update --init --recursive` in the chatterino2-folder after cloning as described here https://github.com/fourtf/chatterino2#building

**Comment by Heermod** [comment]
New problems

In file included from ../chatterino2/src/common/Channel.hpp:5:0,
                 from ../chatterino2/src/singletons/WindowManager.hpp:3,
                 from ../chatterino2/lib/appbase/appbase/main/singletons/Fonts.cpp:11:
../chatterino2/src/messages/LimitedQueue.hpp:233:5: error: ‘qsizetype’ does not name a type; did you mean ‘iswctype’?
     qsizetype space()
     ^~~~~~~~~
     iswctype
../chatterino2/src/messages/LimitedQueue.hpp: In member function ‘std::vector<T> chatterino::LimitedQueue<T>::pushFront(const std::vector<T>&)’:
../chatterino2/src/messages/LimitedQueue.hpp:114:53: error: ‘qsizetype’ does not name a type; did you mean ‘iswctype’?
                 std::min(this->space(), static_cast<qsizetype>(items.size()));
                                                     ^~~~~~~~~
                                                     iswctype
../chatterino2/src/messages/LimitedQueue.hpp: In member function ‘bool chatterino::LimitedQueue<T>::deleteFirstItem(T&)’:
../chatterino2/src/messages/LimitedQueue.hpp:253:13: error: there are no arguments to ‘space’ that depend on a template parameter, so a declaration of ‘space’ must be available [-fpermissive]
         if (space() > 0)
             ^~~~~
../chatterino2/src/messages/LimitedQueue.hpp:253:13: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-class-memaccess’
Makefile:2484: recipe for target 'Fonts.o' failed
make: *** [Fonts.o] Error 1

**Comment by pajlada** [comment]
As mentioned in the comment in the BUILDING_ON_LINUX document https://github.com/fourtf/chatterino2/blob/master/BUILDING_ON_LINUX.md#linux you need Qt 5.10 or newer. I'm guessing your version of Ubuntu does not have that.
Your options are:
1) Manually install a newer Qt version
2) Add a PPA that includes a newer Qt version
3) Upgrade your Ubuntu to a version that has Qt 5.10 or newer. 18.10 or 19.04 would work

**Comment by Heermod** [comment]
For Qt
https://unix.stackexchange.com/questions/481063/ubuntu-18-04-1-lts-x64-how-to-update-qt-5-10-from-qt-5-9-5
for lboost_filesystem 
apt-get libboost-filesystem-dev
Worked like a charm

**Comment by Heermod** [comment]
SSL problems occurred so installed couple of libssl and it fixed a problem.

**Comment by The-Renaissance** [comment]
Qt5 has moved to an online installer and the original installer files cannot be found any more 😢

**Comment by fourtf** [comment]
You can see all available at versions for direct download here: http://download.qt.io/official_releases/qt/

**Comment by The-Renaissance** [comment]
Thank you @fourtf, very cool!

On Aug. 17, 2019 1:20 p.m., fourtf <notifications@github.com> wrote:

You can see all available at versions for direct download here: http://download.qt.io/official_releases/qt/
