### ISSUE TITLE
Suggestion: Mod icon on by default.

### ISSUE THREAD

**Issue by Oscillate1** [fourtf/chatterino2#1036]
This may be already in the works, but simply put, the mod icon in the top right should have an option to be on by default, when Chatterino 2 is launched.  :)

Thanks for all the great work!

![mod_icon](https://user-images.githubusercontent.com/26865638/56859204-76eeaa00-6955-11e9-9ee2-4d0906f3b1be.jpg)

**Comment by TranRed** [comment]
It should save its state in newest nightly. So you atleast have to click it only once now. See Issue: #661
Might be helpful for you to know :)

**Comment by pajlada** [comment]
Yeah, please try out the latest Chatterino2 Nightly release (available under github releases) and try the mod state saving out. If it's still an issue, please re-open this issue and let me know what's lacking

**Comment by Oscillate1** [comment]
Yeah, that fixed it.  Thanks a lot, also some other changes made are nice, keep up the great work guys.
