### ISSUE TITLE
The invisible character is no longer added for identical messages

### ISSUE THREAD

**Issue by yobson1** [fourtf/chatterino2#1054]
It just isn't added anymore, I get the error from twitch than I cant send an identical message.

**Comment by TranRed** [comment]
are you using the latest nightly?

**Comment by yobson1** [comment]
> are you using the latest nightly?

yes

**Comment by TranRed** [comment]
Strange. I can't reproduce the problem. Works for me with the new character that was added last week. Just re-tested it again on current nightly based on the latest commit 30430b0

![grafik](https://user-images.githubusercontent.com/16636423/57168047-5f556c80-6e00-11e9-80aa-4237415ae222.png)

**Comment by yobson1** [comment]
never mind, im dumb. idk why it stopped working in the first place but downloading the latest nightly version fixed it. when i re-downloaded it the first time i downloaded the installer, not the nightly.
