### ISSUE TITLE
Whispers don't work

### ISSUE THREAD

**Issue by pajlada** [fourtf/chatterino2#1067]
Right now it's not possible to send whispers from Chatterino.

We currently send whispers through IRC, by sending `/w TARGET_USERNAME MESSAGE` to the `#jtv` channel.

When sending a message, we receive a notice message back from TMI stating our whisper was not sent due to our settings.
Message: `14:59 Your settings prevent you from sending this whisper. `

Relevant discussion on the Twitch Developers forum: https://discuss.dev.twitch.tv/t/unable-to-have-my-bot-send-whispers/21120

**Comment by apa420** [comment]
Not sure if relevant but all whispers that get sent go throught the channel: "jtv"

**Comment by pajlada** [comment]
Works now, if this is still an issue for someone please let me know

**Comment by rezow** [comment]
I'm having this problem

**Comment by pajlada** [comment]
> I'm having this problem

Please open a new issue with any details you can provide (what error message you get, your twitch username etc)

**Comment by pajlada** [comment]
@rezow :point_up:
