### ISSUE TITLE
System error 

### ISSUE THREAD

**Issue by blarbimus** [fourtf/chatterino2#1070]
The code execution cannot proceed because libssl-1_1-x64.dll was not found. Reinstalling the program may fix this problem.
Reinstalled, still not fixed it.

**Comment by pajlada** [comment]
1. Make sure you downloaded it from https://github.com/fourtf/chatterino2/releases/tag/nightly-win
2. Make sure you haven't moved the chatterino.exe file out of the folder it came in. If you want to be able to launch it from another place, make sure you don't move or copy the chatterino.exe file, but rather make a shortcut and ensure that the shortcut still launches the exe from the correct folder (the one with libssl-1_1-x64.dll in it

If you still need help, please let me know

**Comment by pajlada** [comment]
3. Make sure you've extracted chatterino from the archive. You can not run chatterino from the archive, you must have extracted the entire folder.
