### ISSUE TITLE
Static emote rendering issue

### ISSUE THREAD

**Issue by matijakevic** [fourtf/chatterino2#119]
When someone types some static emote in chat it won't show up until chat receives new message.
For example

chatter: KKona (doesn't render)
chatter: test (KKona renders)
chatter: KKona (both KKona render)
chatter: 4Head (4Head doesn't render)
chatter: test (4Head and KKona render)

I assume that when emotes are received, re-rendering isn't called until next message comes.
GIFs are automatically updated and re-rendered because they have some update code behind them for animation.

**Comment by pajlada** [comment]
The emote issue is fixed, there's still an issue with dynamically loaded badges though
