### ISSUE TITLE
Threaded image loading crashes the program

### ISSUE THREAD

**Issue by matijakevic** [fourtf/chatterino2#122]
When many emojis/emotes are written in chat at once, Chatterino spawns that many threads for loading LazyLoadedImage which crashes the program.

Solution is probably to just spawn a few threads that will take care of queue of images that need to be loaded. This problem should also be automatically resolved if QWebEngineView gets fully implemented in Chatterino for rendering messages which I am currently working on.

**Comment by pajlada** [comment]
Fixed by @hemirt in e7e4ab768b53a6c2138544ab2125fd372b32d048
