### ISSUE TITLE
when user is set with invalid oauth, wont connect to twitch

### ISSUE THREAD

**Issue by hemirt** [fourtf/chatterino2#132]
When the user is not Anon, e.g. "hemirt" but his oauth is invalid
[relevant](https://github.com/fourtf/chatterino2/blob/881e695189087034e9ad03aea9aa2e4f4a83dbd4/src/ircmanager.cpp#L82)

the socket just kept on being in the status "connecting" and didnt connect (and didnt timeout either)

**Comment by pajlada** [comment]
So we should identify the response that the IRC server sends when an invalid login is given and handle it correctly

**Comment by fourtf** [comment]
This should at least print an error message in chat when it can't connect because of an invalid oauth

**Comment by pajlada** [comment]
Seems to work fine in the latest build, you get a proper message saying your login credentials are bad. Feel free to re-open if you disagree @hemirt
