### ISSUE TITLE
Import user accounts from Chatterino 1

### ISSUE THREAD

**Issue by pajlada** [fourtf/chatterino2#133]
File location: `%APPDATA%/Chatterino/Login.json`
File format:
```json
[
  {
    "Username": "pajlada",
    "OauthToken": "1b1b1b1jjskgjsgk3mgk3jgksn",
    "ClientId": "bn34hfn2krbn1kfbnfjfbn2f"
  },
  {
    "Username": "testaccount_420",
    "OauthToken": "1b1b1b1jjskgjsgk3mgk3jgksm",
    "ClientId": "bn34hfn2krbn1kfbnfjfbn2e"
  }
]
```
`oauth:` not included in the `OauthToken` field (which is good)

**Comment by fourtf** [comment]
Doesn't seem useful to me. I doubt anyone will have a problem with logging in again and the feature will lose it's helpfulness after the initial release of Chatterino 2.
