### ISSUE TITLE
Adding possibility to launch new instance/card through command parameters

### ISSUE THREAD

**Issue by sadiablos** [fourtf/chatterino2#136]
Possibility to launch chatterino with something like "-c monstercat" which would open new instance/new card/make active opened one that would help integrate this as an option for Streamlink Twitch GUI

**Comment by fourtf** [comment]
duplicate of #136

**Comment by sadiablos** [comment]
Wait, what?

**Comment by Yardanico** [comment]
Lol

**Comment by fourtf** [comment]
Changed the link of the duplicate issue in my last post.

Thanks for insightful comments such as "Wait, what?" and "Lol", very helpful.
