### ISSUE TITLE
Improve tooltip system

### ISSUE THREAD

**Issue by pajlada** [fourtf/chatterino2#157]
Should most likely be its own `QWindow`/`QWidget` so it can fit with the user-selected style. It might be able to re-use a lot of the on-hover-timings already implemented for the simple tooltip system.

**Comment by Cranken** [comment]
Open PR for it: https://github.com/fourtf/chatterino2/pull/158

**Comment by pajlada** [comment]
Fixed by @Cranken in https://github.com/fourtf/chatterino2/pull/158
