### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by ladspeak** [fourtf/chatterino2#160]
Hi there. Love the Twitch chat client you make; literally use it all day every day.

I don't want to be that guy that basically begs for you to things I want, but I just have a few feature suggestions that you could implement if you like them.

1. with BTTV you can hold down CTRL (left) to essentially pause the chat, which makes it much easier to read a message if a chat is moving fast, or if you want to copy one for example. I understand that you can simply scroll up to keep the chat from moving but sometimes it doesn't suffice as a message may be the most recent one so scrolling up would simply hide the one you potentially might be targeting.

2. A setting to increase the amount of lines that are saved in the chat pane; again, similar to what BTTV has.

3. Perhaps a chat logging feature; clicking the downwards arrow and then have a checkbox which enables chat logging where all messages are saved to a text file

**Comment by pajlada** [comment]
Hey, what do you mean by the third feature? Do you mean just logging all channel messages to a file (like `logs/forsenlol-2017-12-26.txt`?

**Comment by fourtf** [comment]
The feature requests have been broken into smaller issues to increase readability.

1. #208
2. #11
3. #6
