### ISSUE TITLE
Randomly crashes when using tabs/splits

### ISSUE THREAD

**Issue by fourtf** [fourtf/chatterino2#165]
Always crashes when:
- renaming splits

Sometimes crashes when:
- switching tabs
- deleting tabs
- removing splits

also seems to happen more often when switching into a channel that is very active

**Comment by Cranken** [comment]
If you delete the splits from the page before deleting the page then some crashes won't happen anymore like closing a tab when there are still splits open.

Also crashes when:
Empty Tab -> Press "Add chat" / CTRL+T -> Close/cancel the dialog -> Close tab -> Crash
