### ISSUE TITLE
Profile Button Text invisible on KDE

### ISSUE THREAD

**Issue by Ian321** [fourtf/chatterino2#174]
![](https://i.imgur.com/sYwrbcJ.gif)

**Comment by Bur0k** [comment]
With Breeze Dark i get perfect results.
Normal Breeze i see the buttons but not the info that you are able to see.

**Comment by Ian321** [comment]
I made ran a small test with all themes I had:

|theme|visible|text|background|
|--------|--------|----|---------------|
|breath|barely|white|almost white|
|Breeze|invisible|white|white|
|Breeze Dark|yes|white|black|
|Oxygen|yes|black|white|
