### ISSUE TITLE
Menu buttons on OSX become highlighted when setVisible is done

### ISSUE THREAD

**Issue by coral** [fourtf/chatterino2#190]
![screen shot 2018-01-01 at 18 48 57](https://user-images.githubusercontent.com/2163363/34473201-773dff4e-ef24-11e7-8eca-11695c743826.png)

Here's how it looks like on a channel.

**Comment by Cranken** [comment]
Does this still happen? And do the focus frames appear on the "Follow", "Ignore", "Disable/Enable Highlights" buttons?

Also Qt doesn't really offer more options to disable the focus frame other than disabling the "[Qt::WA_MacShowFocusRect](http://doc.qt.io/qt-5/qt.html#WidgetAttribute-enum)" attribute. Maybe it has something to do with the way the focus of the buttons is being proxied to the parent widget but that shouldn't be the case according to the Qt docs.
