### ISSUE TITLE
Emote highlight doesn't display emote on OSX

### ISSUE THREAD

**Issue by coral** [fourtf/chatterino2#192]
![screen shot 2018-01-01 at 18 51 00](https://user-images.githubusercontent.com/2163363/34473211-be389a08-ef24-11e7-8408-85e0f66d6b41.png)

**Comment by fourtf** [comment]
Do any other tooltips work or are they all broken?

**Comment by coral** [comment]
Nope actually all tooltips are broken @fourtf
