### ISSUE TITLE
Things that don't scale properly

### ISSUE THREAD

**Issue by fourtf** [fourtf/chatterino2#202]
red bar under the tab bar
![](https://user-images.githubusercontent.com/6320036/34543067-68a3284e-f0df-11e7-8bcd-b73edc77e779.png)

these boys
![clevernursingimage](https://user-images.githubusercontent.com/6320036/34543131-a7d9b65e-f0df-11e7-8498-62bdef40af2d.png)

**Comment by coral** [comment]
@fourtf i changed the emote button to be an SVG now so as long as you figure out the high dpi shit it should look nice!
