### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by fourtf** [fourtf/chatterino2#21]
- [x] Ctrl + P for settings
- [x] Ctrl + T for new split
- [x] Ctrl + W to close current split
- [x] Ctrl + 1-9 to select tabs
- [x] Ctrl + [Shift] + Tab to switch tabs
- [ ] Hotkey to open new tab
- [ ] Hotkey to close tab

**Comment by pajlada** [comment]
I went with CTRL+SHIFT+T to Open a new tab and CTRL+SHIFT+W to close the current tab. Only thing I think might be worth considering (which is feedback from Axelinho95) is whether or not CTRL+SHIFT+T Should also add a split in the newly created tab.
