### ISSUE TITLE
Ability to lock the tabs

### ISSUE THREAD

**Issue by Trizze** [fourtf/chatterino2#211]
I would like to be able to lock tabs so I don't accidentally press the x and close them while swapping between tabs =)

(To close them I would have to unlock the tab before closing it)

I was told to write this suggestion here, sorry if I wrote it in the wrong place.

**Comment by TranRed** [comment]
I like that one. I always close tabs on accident in legacy chatterino, when I go full forsenE.

**Comment by fourtf** [comment]
This seems like a "hacky" solution for the problem that doesn't actually fix it for anyone who does not search around in the settings or just overlooks it. I would prefer to have a confirmation dialog pop up whenever you attempt to close a tab that has multiple splits in it.
