### ISSUE TITLE
Moderation Card/Tools

### ISSUE THREAD

**Issue by wigoor** [fourtf/chatterino2#217]
Features i'd like to see for moderation:

- [ ] Clicking a user in chat to bring up a moderation card with the users chat messages THIS session.
	- [x] Ability to add Timeout buttons: 2min, 5min, 30min, etc. Custom commands? !permit
	- [ ] Ability to keybind those buttons.
	- [x] Ability to see how long ago the user registered the account.
- [ ] The ability to set a modifier key to stop chat from scrolling while its held down.

**Comment by fourtf** [comment]
Edited your comment to add checkboxes next to the items
