### ISSUE TITLE
Hover-labels mess up tiling window manager

### ISSUE THREAD

**Issue by hptk** [fourtf/chatterino2#218]
I'm using a tiling window manager (i3) on Ubuntu 17.10

Please observe the screenshot below. Note how the right side of the screen is black with "Twitch Subscriber" at the top. The mouse is invisible in the screenshot but is hovered over a subscriber icon on the right side of chat. This is (I suspect) supposed to be an on-hover label, but with tiling widows it consumes half the screen. With a rapid moving chat this can lead to a flickering behaviour where the chat window jumps back and forth between full and half width.

The on click windows when clicking on user names work fine.

![](https://i.imgur.com/7g6njIu.png)

**Comment by Bur0k** [comment]
Can you test it again with the latest commit

**Comment by hptk** [comment]
Now works! Thanks

**Comment by fourtf** [comment]
fixed in #222
