### ISSUE TITLE
more sites than twitch

### ISSUE THREAD

**Issue by maxmotivated** [fourtf/chatterino2#219]
can u make it work on CB too. would be nice to chat on both sites at the same time.

**Comment by fourtf** [comment]
What is a "CB"?

**Comment by maxmotivated** [comment]
ChaturBate dot com

**Comment by maxmotivated** [comment]
a simple: i cant or i dont want to, would be enough. at least the emotes work always on CB.

**Comment by fourtf** [comment]
It is currently on the baglog. There is a lot to do and I do not have time to check out every issue and check out how it would be implemented and write a comment explaining it.

I do right now not have an opinion about this issue.

**Comment by TranRed** [comment]
I just did a quick google search. Doesn't look like you can connect to their chat via IRC.

**Comment by fourtf** [comment]
closing this meme
