### ISSUE TITLE
Appearence Settings take a while to be applied on old messages

### ISSUE THREAD

**Issue by TranRed** [fourtf/chatterino2#230]
Nightly: 8deb096

**TCappearanceSettings / Change Theme**
takes a while to update the whole window
![image](https://user-images.githubusercontent.com/16636423/34913919-f834d544-f908-11e7-8c1f-844de0b02fd4.png)

**TCappearanceSettings / Change Fontsize**
old messages are not resized properly
![image](https://user-images.githubusercontent.com/16636423/34913915-e23fb33a-f908-11e7-9c37-d9d8f8758cb6.png)

**TCappearanceSettings / Timestamps**
takes a while to update timestamps of old messages
![image](https://user-images.githubusercontent.com/16636423/34913933-31664c4e-f909-11e7-9b89-e551c9ad010d.png)

**Comment by fourtf** [comment]
broke it in the refactor
