### ISSUE TITLE
Ignore settings

### ISSUE THREAD

**Issue by TranRed** [fourtf/chatterino2#236]
Nightly: 8deb096

Options regarding ignoring users/certain messages are still missing completely

**Comment by TranRed** [comment]
I think this is also dependent on the list required for #247

**Comment by fourtf** [comment]
work started in #668

**Comment by TranRed** [comment]
do you mean #256 ?

**Comment by fourtf** [comment]
I was referencing the commit, not the issue.

**Comment by pajlada** [comment]
Basic ignore user functionality has now been implemented.
Ignore "messages" functionality is still missing

**Comment by pajlada** [comment]
Ignore messages functionality implemented in 15b432a4cf10fb2cc02f10b97d209917a45f9d93

For more advanced ignore settings, a new issue should be created
