### ISSUE TITLE
Tabbing options missing

### ISSUE THREAD

**Issue by TranRed** [fourtf/chatterino2#242]
Nightly: 8deb096

**TCusernameTabbing**
Options from chatterino1 are not yet available.
![image](https://user-images.githubusercontent.com/16636423/34914071-38ac7a52-f90c-11e7-9c0b-e9aee4604817.png)

**Comment by fourtf** [comment]
This will be fixed eventually and I will forget to close this issue, so I'm just going to close it ahead of time.
