### ISSUE TITLE
Check Boxes in behaviour settings

### ISSUE THREAD

**Issue by TranRed** [fourtf/chatterino2#243]
Nightly: 8deb096

Enabling/Disabling the checkboxes in the behaviour settings always (un-)checks all four boxes

![2018-01-14_08-44-59](https://user-images.githubusercontent.com/16636423/34914116-7b4ea740-f90c-11e7-9370-85092eb6f09f.gif)

**Comment by fourtf** [comment]
broke it in the refactor
