### ISSUE TITLE
Emote tooltip placement

### ISSUE THREAD

**Issue by bennyhillthebest** [fourtf/chatterino2#250]
Right now the the placements of the tooltip on the bottom right brings the problem that if the emote is too far to the right the tooltip is cutted and not readable.
Is it possible to change the placement of the tooltip on the bottom left, or maybe have the choice of left/right? Probably the best solution would be a dynamic one but i don't know how much it could be feasible
![istantanea_2018-01-20_13-43-28](https://user-images.githubusercontent.com/5823707/35183943-7f0ac88c-fdee-11e7-8c94-781c0337f621.png)

**Comment by fourtf** [comment]
related: #177
