### ISSUE TITLE
Cycling through emotes via tabbing includes only global emotes

### ISSUE THREAD

**Issue by bennyhillthebest** [fourtf/chatterino2#251]
I am unable to select FFZ and BTTV channel-only emotes via tabbing. I am unsure about sub emotes.

**Comment by fourtf** [comment]
duplicate of https://github.com/fourtf/chatterino2/issues/251

**Comment by bennyhillthebest** [comment]
Duplicate of #251? It is #251...

**Comment by fourtf** [comment]
Sport I meant #186
