### ISSUE TITLE
Batching messages

### ISSUE THREAD

**Issue by apa420** [fourtf/chatterino2#255]
If possible a batch feature would be appreciated where for example messages sent the latest 0.125s appear all at once. Helps when modding chat.

**Comment by fourtf** [comment]
There will also be a setting for pausing the chat while hovering it which will fix the issue of actually hitting the ban hammer button with your mouse. (I'm assuming that's the issue with modding the chat)

**Comment by fourtf** [comment]
I don't think that this would actually benefit modding, pausing on hover would do a far greater job.
