### ISSUE TITLE
Replace blacklisted words with xxx or *** instead of removing the entire message

### ISSUE THREAD

**Issue by cineafx** [fourtf/chatterino2#26]
Instead of blocking the entire message just replace the blocked word with *** like FFZ does https://i.nuuls.com/JZ52d.png

Maybe make it optional or even on per channel basis.
For example: Block all messages with weeb emotes in forsens chat but only replace them with xxx / *** in all other channels.

**Comment by gempir** [comment]
@cineafx Both links end in a 404

**Comment by cineafx** [comment]
I got no clue why the imgur link is broken. I never deleted it. Maybe some inactivity stuff? Will fix when I come home.

The Chatterino 1 issue link is broken because issues got disabled in the chatterino 1 repository.

**Comment by gempir** [comment]
This should definetly be optional. Since some users just prefer the message completly gone.

**Comment by cineafx** [comment]
Updated with new link and yes I agree it should definitely be optional!

**Comment by hemirt** [comment]
You'd probably want to be able to replace `text phrase` with either `text phrase` _default: `xxx` (or *\**?)_ or `regex phrase` and also have the option to remove full message, I think

**Comment by pajlada** [comment]
Currently being worked on in #587 by @hemirt
