### ISSUE TITLE
Graphical glitch after changing the theme color

### ISSUE THREAD

**Issue by Danis-xD** [fourtf/chatterino2#266]
After you use this slider https://i.imgur.com/wTyaQNs.png 
This happens https://i.imgur.com/OUbgqar.png https://i.imgur.com/8qdXd91.png https://i.imgur.com/OUbgqar.png 
In order to fix it you should close chatterino completely (closing settings window doesn't work)
 (happens on Manjaro Linux)

**Comment by Chronophylos** [comment]
you can use `![](your link)` to embed a image
