### ISSUE TITLE
Add regex for Highlighting, Commands, Ignored Messages and Ignored Users

### ISSUE THREAD

**Issue by Chronophylos** [fourtf/chatterino2#267]
I got this idea when I took a look at [TC](http://gettc.xyz)

**Comment by fourtf** [comment]
Added regex for highlights. Regex for ignored messages will most likely be implemented soon as well.

I don't know what regex for commands would do and  it doesn't seem reasonable for ignored users.

**Comment by fourtf** [comment]
Regexes for ignores is implemented now.
