### ISSUE TITLE
Open in streamlink fails to work

### ISSUE THREAD

**Issue by asasisa** [fourtf/chatterino2#275]
Clicking open in streamlink shows the following in console: 
![image](https://user-images.githubusercontent.com/36403313/36091635-4849b57e-0fdc-11e8-8eac-723f1a996db7.png)
The path seems to be correct, and streamlink works fine otherwise manually opened. 
This is on Manjaro Linux, if it matters

**Comment by Chronophylos** [comment]
did you add anything in "additional arguments"?
and what comes after the last line?

**Comment by asasisa** [comment]
additional args are empty
those are the only 2 lines that are output, nothing comes after them

**Comment by Chronophylos** [comment]
Hm, on linux it doesn't work at all for me but on windows it does.

**Comment by Confuseh** [comment]
I probably fucked up with the position of the additional arguments / didn't handle empty strings - I'll have a look somewhere this week, but shouldn't be too difficult to resolve.

**Comment by Yardanico** [comment]
Hmm, I've made a simple bash script:
```bash
#!/bin/bash
echo $@
streamlink $@
```
And changed streamlink path in Chatterino to point to that script, and now it works. And arguments are fine too.
P.S.: Are there any plans on embedding streamlink output directly in chatterino? It would be much more useful :)

**Comment by Chronophylos** [comment]
fourtf actually added something like that but removed it due to license problems iirc
