### ISSUE TITLE
tabbing priority words list

### ISSUE THREAD

**Issue by hemirt** [fourtf/chatterino2#280]
you would create a group
for example
_Kap_
and then a list of prioritized words (in order)
_KappaRoss KappaClaus Kapp Kappa KappaW_ (could also be a username)
then when you write and press tab (\<TAB\> represents the tab key press)
_Kap\<TAB\>_ -\> the first completed word would be _KappaRoss_, another \<TAB\> -\> _KappaClaus_, \<TAB\> -\> _Kapp_, \<TAB\> -\> _KappaW_, \<TAB\> other emotes starting with _Kap_ (this should be sorted, see  https://github.com/fourtf/chatterino2/issues/57#issuecomment-368921844 )

If you write _Kappa_ \<TAB\> -\> _KappaRoss_, \<TAB\> _KappaClaus_, \<TAB\> _Kappa_, \<TAB\> -\> _KappaW_, \<TAB\> -\> other emotes starting with _Kappa_

you probably should be able to create your own words (that means that the tabbed thing doesnt actually have to be a username or an emote, but a word you like to use (or maybe even a sentence? _just\<TAB\>_ -\> _Just get a house 4House_ ))

should be case  **in**sensitive

also maybe a setting for prefer full emote first (like when in the example you write Kappa you would actually get Kappa first because you wrote the full emote)

**Comment by Yardanico** [comment]
That would be the best feature for watching streams FeelsG <TAB> -> FeelsGoodMan Clap
