### ISSUE TITLE
Holding ctrl + enter locks chatterino 2 

### ISSUE THREAD

**Issue by notheowner** [fourtf/chatterino2#284]
This issue appears both mod and non-mod.
If you hold ctrl + enter to send something the whole chat client locks after a while and you are unable to send messages. You can see incoming ones but can not send. You can send messages once you restart the client. From my point of view looks like a conflict with the global ban protection function.

I recorded some clips in case what I typed above doesn't make sense
part1: https://streamable.com/pehdn
part2: https://streamable.com/6i9as

**Comment by LajamerrMittesdine** [comment]
I believe this bug is fixed. I am not able to reproduce it even after spending a minute holding down ctrl + enter some text in my own channel.
