### ISSUE TITLE
Timeouts rendering

### ISSUE THREAD

**Issue by gempir** [fourtf/chatterino2#295]
Timeouts should be different from normal messages. Maybe similar to Chatterino 1 where the message just lost opacity or use Twitch behaviour and change the text to <message deleted> which you can open to show the message.

#281 describes an option to hide them completly which would be nice aswell.

**Comment by pajlada** [comment]
Fixed to its previous state. There are currently quirks where emotes or badges don't get greyed out, but that can go in a separate issue.
