### ISSUE TITLE
split moving over middle

### ISSUE THREAD

**Issue by hemirt** [fourtf/chatterino2#296]
when you try to move a split like to pin it to the top or to the left or sth, so when you go to pin it to the top from bottom or to the bottom from top, it goes over the like "middle pin" even when it isnt possible to pin it in the middle (aka having only two splits open, or just going over the middle part of one split)

**Comment by hemirt** [comment]
preview here 
https://imgur.com/a/19uZs
https://imgur.com/a/qO0Vu

the same animation mismatch happens when moving a split over a corner position, when that position is not supposed to be available

**Comment by fourtf** [comment]
The issue is phrased to badly that nobody actually understands what the issue is. 

See #302 instead
