### ISSUE TITLE
Dark title bar

### ISSUE THREAD

**Issue by gempir** [fourtf/chatterino2#303]
It would be nice if Chatterino 2 could support a dark Title bar aswell.

In Windows you can do this like this: https://www.howtogeek.com/258162/how-to-add-color-to-inactive-title-bars-in-windows-10/ but this currently doesn't work with chatterino.

The alternative would be somehow using the skin from chatterino and overwriting title color similar to Spotify Windows App maybe.

**Comment by hemirt** [comment]
I would like a also customization not based on currently used windows theme
