### ISSUE TITLE
Crash before the window is created

### ISSUE THREAD

**Issue by Cranken** [fourtf/chatterino2#304]
### Problem
After debugging I've come to the conclusion that this is caused by the custom window frame, 
specifically in the file "[basewindow.cpp](https://github.com/fourtf/chatterino2/blob/master/src/widgets/basewindow.cpp)".
This crash is caused by a segfault with [these](https://github.com/fourtf/chatterino2/blob/master/src/widgets/basewindow.hpp#L55-L61) variables as they are never initialized([here](https://github.com/fourtf/chatterino2/blob/master/src/widgets/basewindow.cpp#L58-L123)) when running it with no WinSDK installed/enabled.
The program then tries to access them regardless of whether you have the WinSDK installed or not so it will crash if you don't have it installed(e.g. [here](https://github.com/fourtf/chatterino2/blob/master/src/widgets/basewindow.cpp#L179) and [here](https://github.com/fourtf/chatterino2/blob/master/src/widgets/basewindow.cpp#L191)).

### (Proposed) Solution
A fix I've found is if you use the define "USEWINSDK" instead of "Q_OS_WIN" in [line 151](https://github.com/fourtf/chatterino2/blob/master/src/widgets/basewindow.cpp#L151).
This will make sure that Windows users without the SDK will never return true to the customWindowFrame.

**Comment by pajlada** [comment]
Fixed in #305
