### ISSUE TITLE
thememanager.cpp won't compile under GCC (7.3)

### ISSUE THREAD

**Issue by Jarel1337** [fourtf/chatterino2#310]
After the 06c3201a1a4c2eaffd37a605af2a5169c3b7cf1e (added dark window to dark theme) commit GCC throws out the following error when trying to compile /src/singletons/thememanager.cpp:
`../src/singletons/thememanager.cpp:92:55: error: no match for ‘operator=’ (operand types are ‘chatterino::singletons::ThemeManager::TabColors’ and ‘<brace-enclosed initializer list>’)
             this->tabs.regular = {fg, {bg, "#ccc", bg}};`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`^`

and goes on for every line in this part of the code
```c++
        if (lightWin) {
            this->tabs.regular = {fg, {bg, "#ccc", bg}};
            this->tabs.newMessage = {fg, {bg, "#ccc", bg}};
            this->tabs.highlighted = {fg, {bg, "#ccc", bg}};
            this->tabs.selected = {"#fff", {"#333", "#333", "#666"}};
        } else {
            this->tabs.regular = {fg, {bg, "#555", bg}};
            this->tabs.newMessage = {fg, {bg, "#555", bg}};
            this->tabs.highlighted = {fg, {bg, "#555", bg}};
            //            this->tabs.selected = {"#000", {themeColor, themeColor, themeColorNoSat}};
            this->tabs.selected = {"#000", {"#999", "#999", "#888"}};
```
The issue only arises on GCC

**Comment by fourtf** [comment]
Could you try changing every `"#xxx"` so it's `QColor("#xxx")` and see if that compiles?

**Comment by Jarel1337** [comment]
Same error with this
```c++
if (lightWin) {
            this->tabs.regular = {fg, {bg, Qcolor("#ccc"), bg}};
            this->tabs.newMessage = {fg, {bg, Qcolor("#ccc"), bg}};
            this->tabs.highlighted = {fg, {bg, Qcolor("#ccc"), bg}};
            this->tabs.selected = {Qcolor("#fff"), {Qcolor("#333"), Qcolor("#333"), Qcolor("#666")}};
        } else {
            this->tabs.regular = {fg, {bg, Qcolor("#555"), bg}};
            this->tabs.newMessage = {fg, {bg, Qcolor("#555"), bg}};
            this->tabs.highlighted = {fg, {bg, Qcolor("#555"), bg}};
            //            this->tabs.selected = {"#000", {themeColor, themeColor, themeColorNoSat}};
            this->tabs.selected = {Qcolor("#000"), {Qcolor("#999"), Qcolor("#999"), Qcolor("#888")}};
        }
```

**Comment by Jarel1337** [comment]
Whoops forgot to capitalize the C in QColor, no it works!

**Comment by fourtf** [comment]
Perfect, you can create a pull request and I'll accept it or I just make the changes myself and commit it. 👍
