### ISSUE TITLE
Timestamps get set wrong

### ISSUE THREAD

**Issue by Cranken** [fourtf/chatterino2#313]
![Example](https://i.imgur.com/8BgIT4s.png)
I can't describe a way to reproduce it, it just happened randomly. The time on my computer was also not 10:51 when the messages came through, it was 10:47 like the later message says.

**Comment by pajlada** [comment]
All except the last message were historical and got their timestamp from the twitch server, while the last message got the timestamp from his own computer which had the time set wrong
