### ISSUE TITLE
Enable smooth scrolling only when X viewers or less

### ISSUE THREAD

**Issue by Cranken** [fourtf/chatterino2#322]
In my opinion having smooth scrolling enabled while watching forsen for example doesn't really look that good, while in slower chats it's way better.
A simple option like "Enable smooth scrolling only when the channel has X viewers or less." would be a nice feature.

**Comment by Evanito** [comment]
I think you mean `Enabled with X viewers or less`, right?

**Comment by Cranken** [comment]
Yes you're correct. Fixed it.
