### ISSUE TITLE
Preload Emotes Startup/Join

### ISSUE THREAD

**Issue by SFFan123** [fourtf/chatterino2#329]
When the client starts (or shortly after that) it should automatically download the emotes (Twitch Global, BTTV Global, FFZ Global) to a cache** (with bandwidth limit*). So if emotes being used they can be displayed immediately.

The channel emotes should be downloaded to a cache** shortly after a channel is joined (also with bandwidth limit*).

This should help people with slower internet to have the full chat experience. And not have blank spaces in chat until a channel gif emote has loaded. On fast chat the emote is out of frame before displayed.

*The bandwidth limit should be like 128KB/s. Or adjustable in settings.
**The Channel cache should be cleared when the channel split is closed/removed **not** when the app is closed.

**Comment by fourtf** [comment]
Right now the whenever an emote gets loaded it gets cached on disk. On restart the image first gets loaded from the disk and then also from the cdn again in case it changed.

It was my intend to add an option to only take the cached image if it is not older than x days.

I don't think that a bandwidth limit can be implemented in a reasonable way.

**Comment by SFFan123** [comment]
But why is it then that some gif emotes are loading so slow in channels that are open for more than a couple hours?
