### ISSUE TITLE
Can't tab original twitch emotes on linux 

### ISSUE THREAD

**Issue by Danis-xD** [fourtf/chatterino2#332]
I can see the original twitch emotes and sub emotes in chat but can't tab them, also they don't show up in the emote menu. 
![image](https://user-images.githubusercontent.com/24809300/38559198-0700559c-3cdb-11e8-83d5-0319365afae1.png)
(BTTV and FFZ emotes work normally) 
I am using Manjaro Linux (arch-based)

**Comment by fourtf** [comment]
You need to log in to see them right now.

**Comment by Danis-xD** [comment]
After restarting it 2-3 times I can tab twitch emotes but they still don't show up in the emote menu.

**Comment by pajlada** [comment]
Fixed in #348
