### ISSUE TITLE
Getting mentions from the chats I already closed

### ISSUE THREAD

**Issue by Danis-xD** [fourtf/chatterino2#343]
I am getting mentions from the chat I already closed. (as you can see there is no channel name after the # symbol on the left)  
![image](https://user-images.githubusercontent.com/24809300/38668549-d2167f64-3e4c-11e8-9fd6-f15915b1f44e.png)
(btw it pings me when someone types the word "Danish" however I only have "Danis" as a highlight word, but I guess you already know about it)

**Comment by LajamerrMittesdine** [comment]
This bug appears to be fixed so far in the latest commit. Not reproducible anymore.

**Comment by pajlada** [comment]
Confirmed fixed for me too, closing the issue
