### ISSUE TITLE
Stop autoscroll while selecting text.

### ISSUE THREAD

**Issue by SFFan123** [fourtf/chatterino2#345]
Stop the autoscroll while text of the chat is selected. To prevent that people copy too much/the wrong thing like the timestamp and the username. Even tho it's a meme, but it can also be annoying.

so people only copy and paste what they want to.

So we get this:

> dead meme nymnOkay

instead of
> dead meme nymnOkay
13:29 pajlada:

**For meme value you can do it settable over a checkbox so the plebs still do it

**Comment by fourtf** [comment]
The chat already gets paused when you select text in chatterino 2
