### ISSUE TITLE
Getting mentions from words that end with highlight

### ISSUE THREAD

**Issue by Ian321** [fourtf/chatterino2#358]
I only have `ian` in my list.
![](https://i.nuuls.com/b3hzd.png)

Edit:
also when it's contained in a string:
![](https://i.nuuls.com/ISQFt.png)

**Comment by fourtf** [comment]
Ruko_ hitting me with that nasty dab in that screenshot 
![1](https://user-images.githubusercontent.com/6320036/39088528-0b04e86a-45b4-11e8-9ebf-8997ed5fe30d.png)
