### ISSUE TITLE
Does not inform you when you disconnect from chatterino

### ISSUE THREAD

**Issue by loitermaster** [fourtf/chatterino2#365]
As far as I am aware, Chatterino only notifies user when they are disconnected from the internet entirely, IE. when disconnected only from Chatterino, "disconnected from chat" message will not appear, only the "reconnected to chat" message when the user is eventually reconnected and able to use Chatterino again.

It is possible that I am misdiagnosing the problem, as I am assuming that the disconnect and reconnect messages mean what they say and this is not some kind of misdiagnosis by the system itself

This is not only frustrating, but can be very misleading as I personally get up to four "reconnected to chat" messages over the course of two minutes while never being reconnected and able to use chat for more than a few seconds total over that two-minute period while the "reconnected to chat" message is still present.

The system either needs to: do away with "reconnected to chat" messages entirely, only informing when one is disconnected-that message disappearing when the user is reconnected, (this being the easy option as it simply does not allow for Chatterino to mislead the user as opposed to actually improving it), or needs to be able to identify when one specifically cannot send messages over Chatterino accordingly as opposed to being disconnected from the internet in its entirety.

paaaajaW

**Comment by fourtf** [comment]
Are you on wifi or lan?

**Comment by loitermaster** [comment]
wifi
I don't doubt that at the moment it says that I'm reconnected I am, it's just that that doesn't help lol

**Comment by fourtf** [comment]
I haven't really tested it much on wifi, I'll have to do that at some point

**Comment by loitermaster** [comment]
<3
