### ISSUE TITLE
[Feature Request] Multi line messages

### ISSUE THREAD

**Issue by Evanito** [fourtf/chatterino2#366]
Typing a message which includes the newline character (\n for example) should, with relevant option(s) enabled:

1. Send the part before the newline character
2. Wait the minimum time between messages (avoid "sending messages too fast" or "slowmode" message)
3. Send the part **after** the newline char
4. Repeat if second part has another newline char

Potential Options:
- Enable multiline messages
- Custom newline character 
- Longest slowmode to wait, otherwise delete newline char and just send all in one

**Comment by fourtf** [comment]
I dislike this option as chatterino might be looked at as a "spam tool" by some people already.

**Comment by Evanito** [comment]
Note the positive reception of duplicate #573

**Comment by fourtf** [comment]
not going to be supported
