### ISSUE TITLE
Display domains as all lowercase

### ISSUE THREAD

**Issue by fourtf** [fourtf/chatterino2#370]
Uppercase i and lowercase L can easily be mistaken for each other.

Adding an option to display the domain names as all lowercase could fix this issue. Copying the link however would still copy the mixed case domain name.

e.g.
`DomAln.cOm/AsfFdgasdf` => `domaln.com/AsfFdgasdf`

**Comment by pajlada** [comment]
I think this should also turn all characters to their punycode variants
i.e. `https://www.аррӏе.com/` would be displayed as `https://www.xn--80ak6aa92e.com/`

**Comment by DatGuy1** [comment]
@pajlada close this?
