### ISSUE TITLE
Switching emotes and emojis tab back and forth makes emotes tab disappear

### ISSUE THREAD

**Issue by TETYYS** [fourtf/chatterino2#383]
Application crashes if user attempts to close emotes window and opening it again:

https://streamable.com/jrwqe

**Comment by fourtf** [comment]
Can you make sure that this happens on the most recent build?

**Comment by TETYYS** [comment]
where are the latest compiled binaries

**Comment by fourtf** [comment]
Now I was able to reproduce it, it only happens when the close button for tabs is enabled.
