### ISSUE TITLE
Create a way to align text

### ISSUE THREAD

**Issue by LajamerrMittesdine** [fourtf/chatterino2#403]
![aligntext](https://user-images.githubusercontent.com/2313104/40202021-c1a18058-59ee-11e8-87f1-3ad7ef3dec44.png)

In Hexchat for example there is a middle bar and all text starts after that point and the username goes out the other way. The middle bar is adjustable and if you go too far to the left it starts to truncate the username.

**Comment by fourtf** [comment]
The effort required is unreasonable given the amount of people that will use this feature
