### ISSUE TITLE
Tags don't show from time to time

### ISSUE THREAD

**Issue by Ian321** [fourtf/chatterino2#404]
![deepinscreenshot_select-area_20180518231146](https://user-images.githubusercontent.com/14338265/40258284-5a8d9fec-5af1-11e8-8798-a765d74e08f5.png)

**Comment by Ian321** [comment]
Maybe cache it ![](https://cdn.frankerfacez.com/emoticon/107715/1)

**Comment by fourtf** [comment]
probably an issue on twitchs side, caching it isn't a good idea
