### ISSUE TITLE
Add the option to copy the text used to display an emote.

### ISSUE THREAD

**Issue by LajamerrMittesdine** [fourtf/chatterino2#410]
When you right click an emote or emoji you get an option to copy the link.

I think an option to copy the text would also be useful.

For example if I right click the emote gachiBASS or emoji \:clap\: it would have an option at the top or bottom to "Copy text". gachiBASS or \:clap\: would be inserted into the clipboard.

**Comment by fourtf** [comment]
I think this option is overkill as it's just the same as copying the emote and pressing Ctrl+C
