### ISSUE TITLE
Chatterino 2 sometimes receives messages in "chunks"

### ISSUE THREAD

**Issue by Yardanico** [fourtf/chatterino2#424]
In channels with fast chat when something happens and everyone writes messages are received in "chunks" and you can send your messages only between those "chunks":
Video showing the problem (notice sometimes when I hit enter message isn't sent):
https://yadi.sk/d/2dgFCt8w3WY3a7

**Comment by fourtf** [comment]
This issue is not related to Chatterino. Twitches chat server can't keep up with the amount of messages so it blocks from receiving messages.

In normal twitch chat it always looks like your message got sent, even if it did not.

**Comment by Yardanico** [comment]
Oh, ok, so twitch chat has a "UX friendly" design so they don't even tell you if your message wasn't sent, eh...
