### ISSUE TITLE
Show emote regardless of if a chatter is subbed to a channel or not.

### ISSUE THREAD

**Issue by LajamerrMittesdine** [fourtf/chatterino2#427]
If it's not against Twitch TOS, it'd be nice to autoreplace text with the appropriate emote.

I see many chatters trying to copy paste emotes and then I just see blocks of text because they aren't subbed.

Maybe not enable it by default as it's not typical behavior but have the option "Autoreplace known emote text with the actual emote."

Edit: This should probably only be done if the emote has been cached by the client already.

**Comment by NotYannickverc** [comment]
stupid idea, why should someone be able to do sub emotes for someone they're not subbed to?

**Comment by LajamerrMittesdine** [comment]
It's mostly not about the person being able to use the emote and more about me not having to read a block of text. There's already extensions for browsers that provide this functionality.

It wouldn't be default behavior. But an option to "Autoreplace emote text with emote" isn't really all that bad. It's just a visual modification allowing choice.

**Comment by NotYannickverc** [comment]
Okay agreed, it should be an option

**Comment by fourtf** [comment]
I dislike the idea as it makes plebs as it makes plebs spam emotes that they don't own. This is against what streamer wants, what legitimate users and subs want and what twitch wants.

**Comment by LajamerrMittesdine** [comment]
Fair enough.
