### ISSUE TITLE
tmi.twitch.tv in new subscription notifications (in chat)

### ISSUE THREAD

**Issue by Yardanico** [fourtf/chatterino2#444]
look at consar here (gachiBASS):
![image](https://user-images.githubusercontent.com/21169548/40928272-923463a0-6829-11e8-95e5-4859d1ef14e7.png)

**Comment by pajlada** [comment]
Fixed in https://github.com/fourtf/chatterino2/commit/7c81477c3562520b87ef44cb7614a25e41529703
