### ISSUE TITLE
Valid Emote Text not getting converted to emote.

### ISSUE THREAD

**Issue by LajamerrMittesdine** [fourtf/chatterino2#448]
![image](https://user-images.githubusercontent.com/2313104/40965076-cf7606dc-687a-11e8-8d44-7c6d20d50b3f.png)

Based on the regex, these 8 combinations should all be valid.
`[oO](_|\\.)[oO]`

o.o O.O o.O O.o are not being properly converted.

**Comment by hemirt** [comment]
My understanding is that the twitch api returns a regex for this emote and that includes dotted variants (eg.  o.O) but doesn't send them in the irc3 tagged message in the "emotes" tag, and only sends the underscored variants (eg. O_o) therefore I think only the tag in the message should be followed and any other parsing of twitch emotes should not happen

**Comment by LajamerrMittesdine** [comment]
Didn't realize this was such a complex issue :sweat: 

Closing this request.
