### ISSUE TITLE
Feature Request: Mobile Apps for Android and iOS

### ISSUE THREAD

**Issue by Xersesxd** [fourtf/chatterino2#457]

**Comment by Yardanico** [comment]
I think it's actually not that hard (but it seems to be much easier for Android than to iOS):
http://doc.qt.io/qt-5/android-support.html
http://doc.qt.io/qt-5/ios-support.html

**Comment by fourtf** [comment]
I'm closing this issue because it is too big of an effort to fit a github issue.
