### ISSUE TITLE
When trying to send a message I semi-occasionally get "sending messages too fast" even if it's my first message.

### ISSUE THREAD

**Issue by LajamerrMittesdine** [fourtf/chatterino2#462]
I've been experiencing this for the past few days. Never noticed it before then.

Other users I've talked to have also noticed it happening.

**Comment by pajlada** [comment]
I have noticed the same, also in my own chat or in chats where I'm a moderator

**Comment by LajamerrMittesdine** [comment]
#501 Discussion seems to be happening there for the same issue. So I'm closing this one.
