### ISSUE TITLE
Contextual tab-completion

### ISSUE THREAD

**Issue by pajlada** [fourtf/chatterino2#467]
Optional feature to prioritize username tab-completions to very recent chatters. Maybe depends on number of chatters?
100 most recent chatters in forsens chat, 20 most recent chatters in mine? Number should be tweakable

This should be an optional feature

Not sure if this should only prioritize the @-version of the username, or also the non-@ -version
Also not sure if it should prioritize the username over emotes or not

**Comment by Chronophylos** [comment]
Also if someone mentions you their name should get prioritized.

**Comment by fourtf** [comment]
I don't see good use in this feature. Pajlada can implement it himself (him being active in a lot of fast channels).
