### ISSUE TITLE
Wayland error

### ISSUE THREAD

**Issue by Jarel1337** [fourtf/chatterino2#469]
Hovering over an emote produces this error:
`
Unexpected wl_surface.enter received for output with id: 11 screen name: "<<Personal screen name>>" screen model: ""
`

**Comment by Jarel1337** [comment]
The error also appears when clicking on profiles, and when doing so the profile is in the top left of my screen, not "in" the chatterino window.
It also comes up when clicking the change user button and the settings menu, so I'm thinking the bug is in the way windows are created.

**Comment by LajamerrMittesdine** [comment]
What distro are you using?

I'm using Fedora 27 and running Wayland by default. Though the application runs in xwayland mode.

Does your distro not have x11 fallback compatibility?

**Comment by Jarel1337** [comment]
Using Gentoo, with xwayland on kwin 5.12.5

**Comment by fourtf** [comment]
Not possible to reproduce for me
