### ISSUE TITLE
Linux autoupdater

### ISSUE THREAD

**Issue by Jarel1337** [fourtf/chatterino2#470]
There is a prompt telling me that I'm running an outdated version of chatterino, however the update option is greyed out so I can't update.

This is on Gentoo Linux

**Comment by fourtf** [comment]
there is no updating mechanic, it is proposed in another issue

**Comment by Jarel1337** [comment]
Okay, the prompt was the crash prompt
screenshot: 
![screenshot_20180614_172834](https://user-images.githubusercontent.com/26655508/41422225-bf7832de-6ff8-11e8-885c-ac1dc1e76e7c.png)
