### ISSUE TITLE
Make user info popup draggable

### ISSUE THREAD

**Issue by DatGuy1** [fourtf/chatterino2#472]
- [ ] Make the widget draggable
- [x] Make the widget not pop up in the bottom right of the cursor. It's pretty annoying just having it pop up at the bottom right and being unable to click some buttons

**Comment by fourtf** [comment]
Fixed dragging for widget on windows https://github.com/fourtf/chatterino2/commit/b2be44bbe798626b000608ce0a7d3a2ba3d87c0b

**Comment by fourtf** [comment]
fixed the center thingy

**Comment by fourtf** [comment]
Only thing left is implemention the the dragging behaviour on linux and mac.

**Comment by pajlada** [comment]
I may have broken the draggability of the popup here e32841ab81145bec33e8a41d6852c56804be1218
