### ISSUE TITLE
Fish like history search

### ISSUE THREAD

**Issue by Jarel1337** [fourtf/chatterino2#473]
It would be cool if you could type <string> and pressing up arrow auto completes it to
<string> FeelsWeirdMan
<string> PagChomp
<string> Kapp

Here is how z-shell implements it: https://github.com/zsh-users/zsh-history-substring-search
Fish source: https://github.com/fish-shell/fish-shell

**Comment by fourtf** [comment]
The amount of people that would use this feature is too small to add it. Furthermore I think that this feature is not as useful in a chat than in a shell.
