### ISSUE TITLE
Fish like autosuggestion

### ISSUE THREAD

**Issue by Jarel1337** [fourtf/chatterino2#474]
In fish previously typed commands/recommendations get shown in a greyed out colour, it would be cool if we could add something similar to Chatterino.

Example use case: I type FeelsW and FeelsWerirdMan is "recommended". Or it recommends a previously typed message.

Screenshots:
![screenshot_20180615_141850](https://user-images.githubusercontent.com/26655508/41467507-12a6ae14-70a7-11e8-9a3c-a4b26c0306ec.png)
![screenshot_20180615_142146](https://user-images.githubusercontent.com/26655508/41467613-759c524e-70a7-11e8-97bf-3973ad6b5f50.png)

Fish source: https://github.com/fish-shell/fish-shell
Z-shell implementation: https://github.com/zsh-users/zsh-autosuggestions

**Comment by fourtf** [comment]
This would be too hard to implement without completely writing our own implementation of a text box which is definitely out of scope.
