### ISSUE TITLE
Random "whitespace" in the chat

### ISSUE THREAD

**Issue by gempir** [fourtf/chatterino2#478]
Sometimes I randomly have a lot of whitespace in my chat. I can't reproduce it reliable but it has happend more than once per day atleast. 

Version: nightly v1.0.445 built 2018-06-14T15:08:57.0000000Z

![](https://i.nuuls.com/P3xzy.png)

**Comment by Yardanico** [comment]
Probably because of NaM emote size?

**Comment by Yardanico** [comment]
Can confirm, I encountered this issue a few times too (AFAIK it can happen after scrolling)

**Comment by gempir** [comment]
I can't reproduce it with NaM 

![](https://i.nuuls.com/LKIgZ.png)

**Comment by DatGuy1** [comment]
For me it just happens randomly and looks like a spot for messages before they are actually loaded

**Comment by SLCH** [comment]
Im blind.
Where are whitespaces ?

**Comment by gempir** [comment]
At the bottom of the chat. It's not a new chat. The chat should be full

**Comment by pajlada** [comment]
I think fourtf has already fixed this, closed for now. If you notice it again, please comment in the issue and I will re-open it.
