### ISSUE TITLE
Ripple effect FPS

### ISSUE THREAD

**Issue by matijakevic** [fourtf/chatterino2#479]
To me it seems that ripple effect buttons have low framerate, so the circle expanding in them kinda 'lags'.
![GIF @ 60FPS](https://user-images.githubusercontent.com/7479297/41507325-dbd61b0a-7230-11e8-914e-5fa9c1ed67db.gif)
GIF is recorded at 60fps

**Comment by fourtf** [comment]
I'm pretty sure that the animation speed is limited by qt and not chatterino itself so I'm gonna close this issue since this can not be fixed.
