### ISSUE TITLE
Userinfopopup not working if in search interface

### ISSUE THREAD

**Issue by DatGuy1** [fourtf/chatterino2#480]
Steps to reproduce: Open search widget (ctrl+f bla bla) and click a name to open userinfopopup. Then clicking one of the buttons doesn't do the intended effect

**Comment by LajamerrMittesdine** [comment]
Can confirm this bug, just tested it.

Only happens in the "Searching in x's history" menu. The moderator buttons do not work. Clicking on follow and ignore do work though.
