### ISSUE TITLE
Beta: Setup Issues

### ISSUE THREAD

**Issue by TranRed** [fourtf/chatterino2#483]
1. It asks for a start menu path, even if that option was unselected in the previous screen.
(2. I was looking for the back button because I'm retarted. Maybe add on in bottom aswell.)

![grafik](https://user-images.githubusercontent.com/16636423/41772666-d0a53d00-7619-11e8-8b48-5690649d916b.png)

![grafik](https://user-images.githubusercontent.com/16636423/41772677-da4b5934-7619-11e8-9ba9-f2a397e9aa43.png)

**Comment by fourtf** [comment]
I don't really care
