### ISSUE TITLE
Error Message when pasting wrong token is inaccessible

### ISSUE THREAD

**Issue by TranRed** [fourtf/chatterino2#488]
The error message just pop-ups in the middle of the screen. But in default placement it will be behind the "Paste Code"-Window and can only be closed via the task bar. It should open in front of the other windows.

![grafik](https://user-images.githubusercontent.com/16636423/41774289-537fd9c4-761f-11e8-8ab1-b29ff909632a.png)

**Comment by DatGuy1** [comment]
I believe it's the same as https://github.com/fourtf/chatterino2/pull/452
