### ISSUE TITLE
Alt Gr toggles Split Overlay

### ISSUE THREAD

**Issue by TranRed** [fourtf/chatterino2#490]
Pressing Alt Gr (i.e. when typing @ ) toggles the Split Overlay. According to "Key Binding" only holding ctrl + alt should do it. Is this behaviour wanted? It's an annoyance while type special characters.

**Comment by fourtf** [comment]
Not sure how to fix this as Alt+Gr is the same as ctrl+alt

**Comment by TranRed** [comment]
maybe change shortcut to ctrl + shift or something

**Comment by fourtf** [comment]
ctrl + shift is using for text selection which is suboptimal

**Comment by fourtf** [comment]
Not an issue but more of a design choice, closing it.

**Comment by karl-police** [comment]
Open it again :)

**Comment by TranRed** [comment]
@Mm2PL this should be solved with #2340, right?
No need to reopen a 3 y/o issue then imho

**Comment by Mm2PL** [comment]
> @Mm2PL this should be solved with #2340, right?
> No need to reopen a 3 y/o issue then imho
@TranRed 
No that PR doesn't do any of these modifier-only shortcuts and it doesn't do shortcuts which also trigger on release. So `Ctrl - Show resize handles` and `Ctrl+Alt - Show split overlay` has to stay (at least for now).
