### ISSUE TITLE
Use emoji long codes

### ISSUE THREAD

**Issue by TranRed** [fourtf/chatterino2#494]
Emojis with short codes will currently display this. This leads to showing the flag of germany as : de : but the flag on nl as :flag-nl: . This leads to inconsistent behaviour for tabbing. Another example might be : +1 : instead of :thumbs_up:

**Comment by pajlada** [comment]
This can be fixed by parsing the `short_codes` array instead of the `short_code` value in the json here https://github.com/fourtf/chatterino2/blob/master/resources/emoji.json
