### ISSUE TITLE
Highlights

### ISSUE THREAD

**Issue by pajlada** [fourtf/chatterino2#50]
Highlight message when your username/custom highlight is mentioned in a message

**Comment by Cranken** [comment]
Started working on this, do we want the custom sounds back? Was this feature even used?
And also, should the sound play/taskbar also flash when the custom highlight is triggered or only when the username is mentioned?

**Comment by pajlada** [comment]
Custom sounds was used a decent amount I think. Yeah I think custom highlights should trigger sound/taskbar flashes too

- [ ] Highlight message in chat
- [ ] Option to play sound when any message is highlighted
   - [ ] Option to choose a custom sound to play
- [ ] Option to flash taskbar when any message is highlighted

Personally I would like per-custom-highlight options so that I can add a highlight that does highlight in chat but doesn't play a sound for example, so something like that might be good to think about already.

**Comment by Cranken** [comment]
How should we implement the taskbar flash feature on linux? I never really used Linux much but I think there's a different taskbar on pretty much every distro. QApplication only gives a solution for Windows/MacOS with [QApplication::alert()](https://doc.qt.io/qt-5/qapplication.html#alert)

**Comment by pajlada** [comment]
Try [QApplication::alert()](https://doc.qt.io/qt-5/qapplication.html#alert) and I'll see what happens on Linux

**Comment by pajlada** [comment]
Base highlighting implemented
