### ISSUE TITLE
Beta: After longer run messages can't be send anymore

### ISSUE THREAD

**Issue by SFFan123** [fourtf/chatterino2#501]
After a runtime of about 4h with chatlogs enabled. On every try to send a message/perform a action chatterino replied "You sending messages to fast." 

System: Windows 7 x64 Pro SP1
Chats open: 3
Version: Beta 2.0.0

**Comment by SFFan123** [comment]
I still receive all the messages and action from others but can't send any.

**Comment by LajamerrMittesdine** [comment]
What happens if you keep chatterino open and do Manual reconnect option? Does the issue fix itself or does it persist.

**Comment by notheowner** [comment]
@LajamerrMittesdine It persists, you have to restart the client completely. For me at least.

**Comment by SFFan123** [comment]
Doing a 7h run atm the bug didn't appear (yet). It seems its not always appearing.

**Comment by SFFan123** [comment]
After 11h the bug occurred.
