### ISSUE TITLE
Change user window opens behind client window if 'window always on top' is enabled

### ISSUE THREAD

**Issue by ch-ems** [fourtf/chatterino2#511]
![capture](https://user-images.githubusercontent.com/40538592/41818838-3c6b21c2-77ae-11e8-99c6-42e1f831dadf.PNG)

**Comment by fourtf** [comment]
fixed

**Comment by ch-ems** [comment]
I was running an old commit, so this can be closed.
 
I found another similar bug though ([demonstration](https://gfycat.com/MeatyBarrenKakapo))
it can be fixed by adding 'Qt:WindowStaysOnTopHint' to the settings dialog flags,
not sure if it's the right solution though.
