### ISSUE TITLE
Whispers split header doesn't change colour on new whisper

### ISSUE THREAD

**Issue by DatGuy1** [fourtf/chatterino2#525]
Sorry, hit enter prematurely :)

I would send a video but it's self explanatory. The font colour of the name  doesn't change to white and the header of it stays grey too.

**Comment by ch-ems** [comment]
adding [this flag](https://github.com/fourtf/chatterino2/blob/6375a902a0936e52a93233e28a21d42852d92f51/src/providers/twitch/ircmessagehandler.cpp#L219) only after we add the message to the whisper channel could fix this.
