### ISSUE TITLE
can't seem to press ok 

### ISSUE THREAD

**Issue by TimIsOverpowered** [fourtf/chatterino2#532]
the ok button can't be pressed when I try to add a new split. Pressing enter works however.

**Comment by ch-ems** [comment]
shrinking and unshrinking the dialog makes the frame not visible and fixes this issue,
maybe that's somehow related.
![532](https://user-images.githubusercontent.com/40538592/41996826-019c3598-7a4e-11e8-9943-665b3c5227a1.gif)

**Comment by fourtf** [comment]
fixed
