### ISSUE TITLE
A too long username makes you unable to chat

### ISSUE THREAD

**Issue by Chronophylos** [fourtf/chatterino2#534]
Testet with `totallystupidlongusername` on `nightly v1.0.544 built 2018-06-27T11:03:59.0000000Z`

**Comment by LajamerrMittesdine** [comment]
I did a test with `TESTING_USERNAME_NO_QUOTE` as the username which is the max length(26 characters).

I was able to send a message both times on the betainstaller build and the master build and have it show up in chat. Others saw it as well.

**Comment by Chronophylos** [comment]
Maybe the problems is because of too many accs. I was having the problem with pretty much every account other than the one chatterino started with. Restarting sometimes helps

**Comment by LajamerrMittesdine** [comment]
How were you selecting / switching through your usernames?

If you were trying to switch from the big settings menu, that doesn't work.

You can only switch from the little cogwheel/person icon menu. Perhaps you were still on "anonymous" and trying to send messages.

Has this still been happening to you?

**Comment by Chronophylos** [comment]
Im sure Im not on anonymous.
I found out that the issue is with twitch. I can send messages but noone receives them.
