### ISSUE TITLE
Collection of UI Errors

### ISSUE THREAD

**Issue by LajamerrMittesdine** [fourtf/chatterino2#538]
1. There are two title bars in Windows.
![image](https://user-images.githubusercontent.com/2313104/42083138-ffc62368-7b57-11e8-9b1f-2a483552205c.png)

2. The "Select a channel to join" menu has 2 title bars as well.
![image](https://user-images.githubusercontent.com/2313104/42089036-b1de3b88-7b69-11e8-9e9a-8be9b6fb210b.png)

3. Userinfo pop-up window isn't drag-gable.

**Comment by fourtf** [comment]
1. 2. Are clones of a different issue.

Please make a separate issue for 3.

**Comment by fourtf** [comment]
didn't notice this issue was rename

**Comment by Chronophylos** [comment]
I can move the userinfo pop-up tho

**Comment by LajamerrMittesdine** [comment]
@Chronophylos I'm on Windows 10 and this error is occurring for me in the master build. What are you running your chatterino on?

**Comment by Chronophylos** [comment]
windows 10 as well and im using the nightly build.
you mean this pop-up ![](https://i.imgur.com/4kDmlGC.png) right?

**Comment by LajamerrMittesdine** [comment]
@Chronophylos Yeah, I can't move mine at all.

**Comment by fourtf** [comment]
I was searching for this issue for 5 minutes because the title is so shit

**Comment by fourtf** [comment]
#3 seems to work for me, if the issue persists then please create another issue

**Comment by LajamerrMittesdine** [comment]
Using the latest build. The issue with 2 title bars persists for me.

**Comment by LajamerrMittesdine** [comment]
The issue with two title bars still persists. And it's gotten worse monkaS
![image](https://user-images.githubusercontent.com/2313104/42221520-49195d8c-7ea0-11e8-9775-5424a714b094.png)

**Comment by LajamerrMittesdine** [comment]
Thanks to @Ian321 we managed to narrow down the issue.

The bug is with Qt 5.11.1 and the dlls that it copied when using winqtdeploy.

Downgraded to Qt 5.11.0 and it works completely fine now.

**Comment by Kllrt** [comment]
I am using version 2.0.4 downloaded from website and I am still having this issue. What is the solution?
