### ISSUE TITLE
Allow custom Cache directory (Like for the logs)

### ISSUE THREAD

**Issue by cineafx** [fourtf/chatterino2#541]
This would allow to sync everything but the Cache and log folder in the cloud.

**Comment by notheowner** [comment]
https://i.imgur.com/CRzKMQu.png
Isn't this folder the cache?

**Comment by cineafx** [comment]
Yes but if want to save chatterino 2 as the portable installation you got the cache folder in the same folder as the install. But now your cloud program has to sync that folder constantly
