### ISSUE TITLE
Freeze: On faster chat auto completion freezes Chatterino completely

### ISSUE THREAD

**Issue by SFFan123** [fourtf/chatterino2#551]
I was is sodapoppins chat during sellout Sunday I wanted to autocomplete ppHop and on the keydown of tab it completly freezes.

**Comment by notheowner** [comment]
Can confirm this, but in general, not just fast chat room, tab-complete is extremely laggy or crashes Chatterino mostly in chat rooms that have a lot of chatters

**Comment by LajamerrMittesdine** [comment]
This issue seems related to both #545 and #405

**Comment by SFFan123** [comment]
I got no high cpu usage by chatterino before/while freeze, not like in #545. Only 12% of a i7-3770K.

**Comment by fourtf** [comment]
Duplicate of #545

@SFFan123 12% in the task manager on your CPU means that the application is using an entire processor thread. (4 cores => 8 threads with hyper-threading)
