### ISSUE TITLE
Cursor resets when typing in the 'Disabled Users' box 

### ISSUE THREAD

**Issue by peacedude** [fourtf/chatterino2#553]
When typing in the 'Disabled Users' box the blinking line jumps back all the way to the top of the box if you are typing too slow or stop typing.

I got a fresh install of Chatterino2 2.0.4.

GIF is just me typing random letters while stopping sometimes or writing slow.

![positiveposhcrayfish-max-14mb](https://user-images.githubusercontent.com/10180242/42167360-254a3b20-7e0e-11e8-9da3-5b6bca684cba.gif)

**Comment by pajlada** [comment]
Can confirm, I've had this issue too

**Comment by fourtf** [comment]
This text input will be replaced at some point

**Comment by pajlada** [comment]
Fixed with #560 through 03b7fae09ef3536b743f15ea33e252a277de9ea9
