### ISSUE TITLE
Chatterino freezes when reconnecting to the internet after long period without internet

### ISSUE THREAD

**Issue by notheowner** [fourtf/chatterino2#566]
I have a WiFi that drops frequently. If Chatterino stays disconnected for too long and then it connects to back to the internet, it will connect to the chat rooms and then the entire program will freeze and become unresponsive indefinitely. 
On my end I can't even access task manager or do anything else at that point(everything on my system becomes really slow), so I am forced to hard reboot my computer.

**Reproduce Steps(How it happens to me at least):** Open Chatterino, disconnect from internet, keep it offline for a long period(the smallest period I noticed was around 5-10 minutes), Connect to the internet again, chat rooms reconnect and then client freezes.

Windows 10 64bit, latest version as of now
4GB RAM
28 Chat rooms open + 2(Mentions and Whispers)

My machine is pretty low end, so this might not be happening at all or maybe it unfreezes at one point on other computers, but usually Chatterino 2 is a pretty smooth experience on my computer without performance problems.

I noticed when the reconnect happens, right before the freezing, offline channels that are hosting someone, are being spammed with the message: Now hosting <channel> and then the freezing happens. I do run a lot of chat rooms but it's usually a smooth experience without big performance issues.

**Comment by apa420** [comment]
I got the same issue, but I can use my pc for stuff (didn't freeze entire pc):
Connected with Wifi and then instantly dc.
Reconnect with Ethernet a min after
![capture](https://user-images.githubusercontent.com/17131426/42446925-578bce0e-8378-11e8-8f7f-3ce4fe70a175.PNG)
![capture2](https://user-images.githubusercontent.com/17131426/42446927-5985723c-8378-11e8-94db-e4e3714521c8.png)

**Comment by fourtf** [comment]
Should have been fixed with the memory leak fixes.

**Comment by apa420** [comment]
![](https://i.nuuls.com/Im8M_.png)
Happened to me today, my router lost internet connection and I had to restart the router and didn't have internet for 5 min
