### ISSUE TITLE
Crashes when removing a command/highlighed word

### ISSUE THREAD

**Issue by KjeldGaming** [fourtf/chatterino2#567]
When i'm trying to add a word or command, i make mistakes. We are all humans but...

When i try to remove it with the **remove** button next to it. The program crashes!
I think that is a bug, right?

**Comment by pajlada** [comment]
@KjeldGaming Which version are you running?

**Comment by KjeldGaming** [comment]
Latest.

**Comment by pajlada** [comment]
@KjeldGaming So "Chatterino Beta 2.0.4"?

**Comment by KjeldGaming** [comment]
Yes yes!

**Comment by pajlada** [comment]
@KjeldGaming What OS are you on? Works fine for me on Windows 10 version 1803

**Comment by KjeldGaming** [comment]
Welp, i'm 96 versions behind cus my laptop can't update.

**Comment by pajlada** [comment]
@KjeldGaming I hope it isn't related to the specific Windows version, but I'll leave investigating this bug for now and wait for Chatterino 2.0.5 or 2.0.6 which will allow you to give us proper crash reports

**Comment by KjeldGaming** [comment]
Sure. For now, lets update my laptop and fix it. hopefully.

And this is what happend when i reported it:
![image](https://user-images.githubusercontent.com/14298033/42292649-4a014612-7fd4-11e8-9b8c-b90c0f8d54a9.png)

**Comment by LajamerrMittesdine** [comment]
When you say latest do you mean Chatterino Beta installer or the master build?
