### ISSUE TITLE
Clicking the dropdown button on a split when open should close it.

### ISSUE THREAD

**Issue by notheowner** [fourtf/chatterino2#568]
Clicking on the channel option button when it's already open, just closes and reopens the window and some other small weird things happening: 
[GIF Link here](https://i.imgur.com/E3e2hP6.gifv)

**Comment by notheowner** [comment]
Forgot to mention this happens only on the latest nightly as of commit 335cbf8

**Comment by fourtf** [comment]
That's how it's supposed to work

**Comment by TranRed** [comment]
@notheowner It also behaves this way chatterino 1 (1.3) and earlier versions of chatterino 2. (2.0.4.)

@fourtf I tried some UIs with more or less comparable buttons (e.g. firefox, edge, ms office, sharex, youtube, twitch and the button on top right of this comment window). They close the menu on the second click. From a user perspective I would expect it to work the same way in chatterino. Same with the mod option button for slow mode, sub mode etc. 

In my opinion it would be better for usability to feed users with their "learned" behaviour (i.e. an existing mental model).
