### ISSUE TITLE
Can't exit viewer list

### ISSUE THREAD

**Issue by DatGuy1** [fourtf/chatterino2#569]
Aside from the fact it's laggy and looks horrible, I can't seem to find a way to actually exit it.

**Comment by notheowner** [comment]
Top left, small transparent button 
![chatterino_2018-07-04_23-01-09](https://user-images.githubusercontent.com/25968992/42292849-3e521094-7fde-11e8-93a2-ef7bce7fa8d1.png)

**Comment by TranRed** [comment]
I experienced the same issue, when I first opened it. I think the UI needs a rework.

**Comment by fourtf** [comment]
https://github.com/fourtf/chatterino2/issues/389
