### ISSUE TITLE
Tab auto-complete

### ISSUE THREAD

**Issue by pajlada** [fourtf/chatterino2#57]
- Tab emotes
 - Tab usernames

fourtf edit:
things missing
- [x] usernames
- [x] get list of everyone in chat for autocomplete every X minutes
   - [x] Setting to only get list of people in chat for chats under X viewers
- [x] clear old usernames from the username completion list
- [x] twitch emotes
- [x] When a username is "re-added" as an "active chatter", the timestamp needs to be updated to ensure it doesn't expire

**Comment by hemirt** [comment]
2425ddbd2c3069ba1f4b2f7506f71711a87a8c74 implements the actual tabbing (tab key) to auto complete.
Does **not** implement actual values (that is emotes, names, ...) to auto-complete

**Comment by pajlada** [comment]
More work done in 3bf111a0914b5afc9bcacfa3d4a762be763ee88a

**Comment by hemirt** [comment]
currently ( 1d1f40bf441944c95c2303edc62ca8f1318b2659 ) the emote tabbing is not sorted

- [ ] sort (alphabetically)

**Comment by gempir** [comment]
Tabbing doesn't seem to use the display name but rather the username. Is this a bug or intended?

**Comment by pajlada** [comment]
Completed in 57e0e85d777d18374b168b39d6df85417878067f

Any further advanced features for auto-complete can be made as separate issues
