### ISSUE TITLE
Channel options menu goes outside of the screen in fullscreen

### ISSUE THREAD

**Issue by notheowner** [fourtf/chatterino2#571]
Reproduce: Go fullscreen, click the options in a channel, options window goes outside of the screen

![2018-07-05_11-25-48](https://user-images.githubusercontent.com/25968992/42311370-5052b588-8046-11e8-8d9d-cd94dd9c418c.gif)

**Comment by ch-ems** [comment]
similar to #517

**Comment by fourtf** [comment]
same as https://github.com/fourtf/chatterino2/issues/572
