### ISSUE TITLE
Make typing \n send multiple messages

### ISSUE THREAD

**Issue by nuuls** [fourtf/chatterino2#573]
Typing 
```wixS1 wixS2 wixS3 \n wixS4 wixS5 wixS6 \n wixS7 wixS8 wixS9``` 
should send 3 messages, separated by `\n`.
No delay when you are mod, 1.2s delay when not. 
<img src="https://cdn.betterttv.net/emote/566ca06065dbbdab32ec054e/1x">

**Comment by Evanito** [comment]
Grumble grumble #366

**Comment by fourtf** [comment]
duplicate of #366
