### ISSUE TITLE
anti duplicate message with twitch commands

### ISSUE THREAD

**Issue by hemirt** [fourtf/chatterino2#578]
when you type `/unban hemirt` and send and type it again (up arrow, enter) it replies to you with `hemirt is not banned from this channel` (or `hemirt is no longer banned from this channel`) and the second one replies with `Usage: "/unban <username>" - Removes a ban on a user.`

**Comment by pajlada** [comment]
The only way this behaviour would work like this is if https://github.com/fourtf/chatterino2/blob/master/src/providers/twitch/TwitchChannel.cpp#L172 returned false even though you were actually a mod. I can't reproduce. If you have reproducible steps, comment and I'll re-open the issue
