### ISSUE TITLE
Text selection not fully copied in a small split

### ISSUE THREAD

**Issue by TranRed** [fourtf/chatterino2#586]
I selected the following text and copied it with ctrl+c
![grafik](https://user-images.githubusercontent.com/16636423/42419969-e2e1cd60-82be-11e8-91b7-631ee63ca2e6.png)

This was transfered to my clipboard. The first line was not copyied. 
"because amateurs make emotes and fuck up the aspect ratio. We have to live with that and keep em. pajlada "

Seems to be an issue with split size. It works fully when I make the split wider:
![grafik](https://user-images.githubusercontent.com/16636423/42419994-591f9b42-82bf-11e8-9751-b343d15d53fe.png)

Original Message if needed for testing.
14:51:05   K9kroz: some good emotes happen because amateurs make emotes and fuck up the aspect ratio. We have to live with that and keep em. pajlada

**Comment by pajlada** [comment]
fixed? probably. open new issue if it's still an issue
