### ISSUE TITLE
Ignore emotes by name

### ISSUE THREAD

**Issue by notheowner** [fourtf/chatterino2#590]
^ Title
It was a Chatterino 1 feature. the list for the emotes could be added next to the Phrases and Users tabs in options.

**Comment by pajlada** [comment]
@notheowner Right now you can ignore emotes through the "Ignored phrases" feature. Is this sufficient for your needs?

**Comment by notheowner** [comment]
Yes, this issue was opened long time ago, way before hemirt's PR was competed. Closing issue. 👍
