### ISSUE TITLE
Sending messages with a single dot at the beggining completely ignores the dot

### ISSUE THREAD

**Issue by notheowner** [fourtf/chatterino2#592]
![2018-07-10_15-39-54](https://user-images.githubusercontent.com/25968992/42510624-3016fbd8-8458-11e8-9642-dcff823ef3eb.gif)

This happens only with single dot. Multiple dots work fine

![chatterino_2018-07-10_15-44-10](https://user-images.githubusercontent.com/25968992/42510631-375cea7e-8458-11e8-941f-a32a45e1c91a.png)

Commit: 91e320e

**Comment by fourtf** [comment]
Not related to chatterino, twitch does this.
