### ISSUE TITLE
Add commands to follow and unfollow users

### ISSUE THREAD

**Issue by pajlada** [fourtf/chatterino2#594]
Usage:
`/follow pajlada` would follow pajlada, and print a message in chat when the follow succeeded (or, if you're already following pajlada)
`/unfollow pajlada` would unfollow pajlada, and print a message in chat when the unfollow succeeded (or, if you're not following pajlada)

Suggested by 0tt1S_T1C in Discord

**Comment by LOOOOLOK** [comment]
that'd be quite useful ,surprised it's not a feature yet

**Comment by pajlada** [comment]
Implemented by @apa420 in #604
