### ISSUE TITLE
Display timeout/ban lenghts better

### ISSUE THREAD

**Issue by Chronophylos** [fourtf/chatterino2#598]
Display `136918 seconds` as `1 day 14 hours 1 minute 58 seconds`

**Comment by LajamerrMittesdine** [comment]
I assumed this was already a thing. As I'm seeing `100 minutes`

**Comment by Evanito** [comment]
@LajamerrMittesdine it only does it for even amounts.

3600 seconds -> 1 hour
3601 seconds -> 3601 seconds 
instead of
3601 seconds -> 1 hour 1 second

**Comment by pajlada** [comment]
I implemented it like that on purpose. In my opinion the verbosity of "1 day 14 hours 1 minute 58 seconds" is not worth the screen clutter.
If anything, I would like to see an option to round the timeouts to a reasonable number.

i.e. 64 seconds = 1 minute
110 seconds = 2 minutes
3605 seconds = 1 hour

**Comment by Chronophylos** [comment]
what about making this an option in the settings?

**Comment by fourtf** [comment]
Display as `1.34 days`

**Comment by Chronophylos** [comment]
so `118400 seconds` -> `1.37 days`
and `4932 seconds` -> `1.37 hours` ?

**Comment by pajlada** [comment]
@Chronophylos yes

**Comment by hemirt** [comment]
make a setting to choose formats of that

**Comment by fourtf** [comment]
Making a setting for this clutters the settings. The originally suggested format is fine.

**Comment by fourtf** [comment]
closed by https://github.com/fourtf/chatterino2/pull/601

**Comment by Chronophylos** [comment]
4 minutes to fast Oof
