### ISSUE TITLE
Logging chat to file

### ISSUE THREAD

**Issue by fourtf** [fourtf/chatterino2#6]

**Comment by pajlada** [comment]
Basic logging is complete again in 2f0844ebd96c8e1dcaad54d938e0a0c77fff0083 , but we want to handle certain messages in special ways so we need to wait for message flags to work again

What's left:
 - [ ] Switch log file upon date change
 - [ ] Unscuff logs settings page
 - [ ] Handle certain message flags in a special way

Currently logging is disabled by default, I think that's good but I'm up for discussions on that.

**Comment by fourtf** [comment]
Message flags do still work

**Comment by fourtf** [comment]
I guess it doesn't xD
