### ISSUE TITLE
Categories / folders

### ISSUE THREAD

**Issue by Nobodysme** [fourtf/chatterino2#623]
Would it be possible to group chats in folders? 

That way people could group all channels by games or something like events.

Thanks!

**Comment by apa420** [comment]
It's really hard to visualize what you are requesting, maybe drawing a image or something similar could make it easier to understand.

**Comment by Nobodysme** [comment]
You know you can have folders in your Bookmarks bar of your browser? 

Something like that for Chatterino

**Comment by fourtf** [comment]
I don't think that this is a proper way of handling big amount of joined channels. Having tabs on the left would fix this issue instead.
