### ISSUE TITLE
weird cursor after writing a non standard character

### ISSUE THREAD

**Issue by hemirt** [fourtf/chatterino2#625]
this issue happens when you write for example € or U+206D (thats the zero-width character start arabic input which is used at the end of the message to send duplicate msgs)
it switches the cursor into a cursor with a weird arrow on it

https://i.imgur.com/7CQv4JE.png (note: the red arrow is pointing to the weird arrow, the red arrow is a post-edit)

**Comment by fourtf** [comment]
not reproducible
