### ISSUE TITLE
Live channels don't show up as live

### ISSUE THREAD

**Issue by notheowner** [fourtf/chatterino2#626]
As of commit  e51c5c6 channels that are live, don't show up as live.
Status doesn't change even If I restart Chatterino.

![2018-07-16_13-03-55](https://user-images.githubusercontent.com/25968992/42753192-c80abb10-88f8-11e8-8a02-db29639d0903.gif)

**Comment by LajamerrMittesdine** [comment]
Can confirm this. Experiencing the same exact issue. 👍

**Comment by fourtf** [comment]
Seems to be fixed now
