### ISSUE TITLE
An option to "block / ignore mass pings"

### ISSUE THREAD

**Issue by cineafx** [fourtf/chatterino2#634]
Shit like this is annoying as fuck ... I know I could just ignore them individually or leave the channel but that is not always a good option.

https://gfycat.com/NippyFewDingo

Maybe an option to not show the ping / sound if more than X chatters are getting pinged by the message.

**Comment by notheowner** [comment]
Pointless feature, it's a really specific case I doubt anyone other than you would use it.

**Comment by fourtf** [comment]
Both ignoring pings from a certain channel and ignoring similar messages seem like better solutions for the problem.
