### ISSUE TITLE
More color palettes for usernames

### ISSUE THREAD

**Issue by derLesh** [fourtf/chatterino2#638]
Chatterino 2 uses a more high-contrast color palette, as Chatterino 1.
Personally, I do not like the new colors, but it would be a neat feature to add several color palettes like FrankerFaceZ offers.

![chatterino color](https://user-images.githubusercontent.com/11671272/43087209-9377eb50-8e9f-11e8-8eb1-a7a35ec87368.PNG)

Left: Chatterino 1 - Right: Chatterino 2

**Comment by fourtf** [comment]
There is no plans of adding this in the future
