### ISSUE TITLE
UI is really broken

### ISSUE THREAD

**Issue by Chronophylos** [fourtf/chatterino2#655]
Using `nightly v1.0.650 built 2018-08-07T21:46:00.0000000Z`
I think I saw this somewhere before but I couldn't find the issue
* i have this gigantic header ![](https://i.imgur.com/Y3sCvJI.png) 
* emotes are too small (and bttv gif emotes are not working) ![](https://i.imgur.com/NDv0IMM.png)
* and this ![](https://i.imgur.com/tascRjR.png)

**Comment by pajlada** [comment]
I think the gigantic header is due to us upgrading to Qt 5.11.1 in the CI, rest is some stuff that's most likely broken during some refactoring being done

**Comment by fourtf** [comment]
Fixed the header for qt 5.11.1.

**Comment by Chronophylos** [comment]
awesome
