### ISSUE TITLE
FFZ and BTTV Channel Emotes not loading

### ISSUE THREAD

**Issue by Chronophylos** [fourtf/chatterino2#657]
`nightly v1.0.660 built 2018-08-09T18:46:58.0000000Z` on windows 10
![](https://i.imgur.com/MFO0Z0I.png)

**Comment by LajamerrMittesdine** [comment]
If I hit "Reload channel emotes" in the split header it will load the BTTV Channel emotes. Still doesn't load the FFZ Channel emotes though.

**Comment by Chronophylos** [comment]
I reloaded the channel emotes but the gif emotes dont work.

**Comment by Chronophylos** [comment]
Seems to be fixed
