### ISSUE TITLE
Save chat moderation state in splits

### ISSUE THREAD

**Issue by wigoor** [fourtf/chatterino2#661]
Chat moderation button doesn't remember its state after a restart.

https://i.imgur.com/o6ux36j.png

**Comment by Cranken** [comment]
Using a build with the latest commit doesn't have this problem anymore so it seems like this issue can be closed.

**Comment by wigoor** [comment]
Still doesn't remember its state after restart, 2.0.4 (c872db3-1)
Problem persists.

**Comment by pajlada** [comment]
fixed
