### ISSUE TITLE
Emote tab completion is now case-sensitive?

### ISSUE THREAD

**Issue by bennyhillthebest** [fourtf/chatterino2#666]
I have built the latest build which re-enables the (live) tag, but, and i don't know if it's voluntary, now emote completion via tab key is case sensitive. At least now the program doesn't hang when all the possible emotes are cycled through and it begins to cycle possible users in the chat list, which is nice.

**Comment by notheowner** [comment]
Can confirm tab completion is now case-sensitive on latest build
