### ISSUE TITLE
Chatterino badge doesn't work

### ISSUE THREAD

**Issue by notheowner** [fourtf/chatterino2#667]
As of commit 44c16f1 Chatterino badge doesn't work 

Latest beta on the left, commit 44c16f1 on the right
![chatterino_2018-08-14_19-15-20](https://user-images.githubusercontent.com/25968992/44104030-75ee2c9e-9ff6-11e8-8dd7-326654184507.png)

**Comment by pajlada** [comment]
Fixed in 56aac47fdee369b188011ffaa33525e6a36d5483
