### ISSUE TITLE
Being able to open streams via Chatterino

### ISSUE THREAD

**Issue by Miladooo** [fourtf/chatterino2#682]
Instead of manually typing in the stream in my browser i thought it would be nice by just pressing the name or a button in chatterino which would make the stream open, primarily for streams that are live.

**Comment by notheowner** [comment]
This feature is already available in Chatterino2 both beta and the latest build
![chatterino_2018-08-26_12-29-39](https://user-images.githubusercontent.com/25968992/44626805-ca72a900-a92b-11e8-8f35-b797540d73b9.png)
