### ISSUE TITLE
emotes split apart in emote menu

### ISSUE THREAD

**Issue by seriousm4x** [fourtf/chatterino2#685]
group them together or show them after each other

![2018-08-27 16_37_42](https://user-images.githubusercontent.com/23456686/44666089-e9e70000-aa17-11e8-8721-591f337b788f.png)

**Comment by seriousm4x** [comment]
group them together or show them after each other

![2018-08-27 16_37_42](https://user-images.githubusercontent.com/23456686/44666089-e9e70000-aa17-11e8-8721-591f337b788f.png)

**Comment by LajamerrMittesdine** [comment]
I assume the emotes at the bottom are the Tier 2 and Tier 3 emotes, right?

**Comment by seriousm4x** [comment]
correct

**Comment by fourtf** [comment]
I think this is fixed
