### ISSUE TITLE
Missing dll files

### ISSUE THREAD

**Issue by RiddareCato** [fourtf/chatterino2#700]
After installing windows 10 I had to reinstall chatterino2 but when I tried to start it there was an error saying I was missing "msvcp140.dll", "msvcr120.dll" & "vcruntime140.dll" After downloading these from the internet it was fixed without any more problems but if you guys are able to shouldn't the chatterino download add these as well?

Thank you

**Comment by 23rd** [comment]
https://github.com/fourtf/chatterino2#downloading

> You might also need to install the VC++ 2017 Redistributable from Microsoft if you do not have it installed already.

**Comment by notheowner** [comment]
For me installing VC++ 2017 wasn't enough
I am pretty sure the missing dlls required an older version, VC++ 2013 if I am correct, and windows wouldn't let you install it after 2017 unless I uninstalled everything and installed the older ones first.

**Comment by pajlada** [comment]
@RiddareCato If you could try installing Visual C++ 2013 runtime files, and let me know if that works that would be nice. thanks!

**Comment by RiddareCato** [comment]
I don't have an issue with it anymore, I downloaded the .dll files from the internet and then it was fixed @pajlada

**Comment by pajlada** [comment]
@RiddareCato Thanks for reporting back, I'll close the issue for now until anyone else stumbles into the issue
