### ISSUE TITLE
50+ messages ignored with no ignore list

### ISSUE THREAD

**Issue by Testing0123** [fourtf/chatterino2#701]
I was watching the pokemon marathon and noticed that multiple times during the stream, a message saying "50 messages ignored" will show.  What's causing this?

![chat](https://user-images.githubusercontent.com/27869649/45013552-d7477900-b05e-11e8-8dfb-3d7ecfa16495.png)

**Comment by pajlada** [comment]
I think that's some sort of overflow control code, where if there are just too many messages to handle it will ignore some messages until it's down to a more reasonable amount (See https://github.com/fourtf/chatterino/blob/master/TwitchIrc/IrcConnection.cs#L132-L164)
However, this is a Chatterino1 issue, and not something that happens in Chatterino2.
