### ISSUE TITLE
Constantly disconnects and reconnects

### ISSUE THREAD

**Issue by R34LP3NGWIN** [fourtf/chatterino2#705]
In any chat I go into it says disconnect from chat, then reconnects, however no messages are ever sent once reconnected. It then loops this cycle. https://i.imgur.com/sXRnhUK.png I kept the program open to wait and see if it would get fixed however after a few hours of it being open, it had used all of the memory on my PC. I closed and reopened it, monitoring the memory usage. After 30 minutes of it being open it was using 3gb ram on my pc.

**Comment by pajlada** [comment]
The constant disconnects and reconnects are more likely an issue with TMI or your internet connection.
The memory leak bug on reconnect is brought up in another issue, so I will close this issue.
Thanks for the report!
