### ISSUE TITLE
Add an easy way to mention a user from the chat

### ISSUE THREAD

**Issue by CaptainFlint** [fourtf/chatterino2#706]
I suggest to add some way of quick adding the name of the particular message's author into the chat editbox (with the @-prefix). I think, the best way to do so is by assigning this functionality to Shift+click or Ctrl+click on the username in the chat window.

Why would I ask for this: when there are many users in the chat, the dialogs become hard to maintain, because there is no way to quickly tag a user for replying. TAB-completion is quite tedious and requires constant attention to select the correct username, which you might not even remember in its exact form (and there may be other users with similar names). It significantly delays interaction, which in active chats is not good.

As an example, in the browser extension BetterTTV this  can be done by double-clicking the username (while single-click still displays the user info). Still, I think that Shift+click or Ctrl+click is better (no delay in single click reaction to distinguish single click from a double).

**Comment by pajlada** [comment]
@CaptainFlint In the latest nightly version (but not the beta version) you can right-click a username to add it to chat, that would fill the need right?

**Comment by CaptainFlint** [comment]
Oh, nice! I didn't think to check the releases tab, sorry. I can see there are quite a number of additions there!
Yes, right-click is perfectly acceptable to me. I've just quickly tried it, seems to be working OK. Thanks!

**Comment by pajlada** [comment]
No worries, we don't have any change-log at all so I don't expect anyone to know what's in the unreleased version. Thank for your well-written feature request!
