### ISSUE TITLE
Join channel dialog: text invisible in light and white themes

### ISSUE THREAD

**Issue by CaptainFlint** [fourtf/chatterino2#717]
The screenshot says it all:

![image](https://user-images.githubusercontent.com/6475044/45818979-df084e00-bceb-11e8-92bf-a85af8148d8b.png)

In Dark and Black themes it's OK.

Version: nightly v1.0.723 built 2018-09-20T11:39:19.0000000Z

**Comment by apa420** [comment]
There is more stuff broken than just that (look at the top border and the emoji-icon at the bottom)
![](https://i.nuuls.com/XCLkU.png)

**Comment by apa420** [comment]
Fixed in #723

**Comment by pajlada** [comment]
Fixed in #723
