### ISSUE TITLE
Chatterino crash on newest master

### ISSUE THREAD

**Issue by apa420** [fourtf/chatterino2#725]
it might have to do with QString thread safety

![](https://i.nuuls.com/bXcWJ.png)

![](https://i.nuuls.com/Mz8dw.png)

**Comment by Chronophylos** [comment]
Have you tried to reset your settings? It seems to have worked for me.

**Comment by apa420** [comment]
I haven't been able to reproduce this bug, so I'm closing this issue, if you can, you can open a new one
