### ISSUE TITLE
Strange character line wrapping with surrogate pair unicode characters

### ISSUE THREAD

**Issue by TETYYS** [fourtf/chatterino2#731]
Characters having higher than 0xFFFF codepoint do not propertly wrap to the next line as seen here:

![chatterino_2018-09-24_18-32-48](https://user-images.githubusercontent.com/3091645/45961966-78a36880-c028-11e8-8428-6b1c78dc3e07.png)

Character in the image is \U000252DC (𥋜)

REL https://github.com/fourtf/chatterino2/issues/730

**Comment by fourtf** [comment]
Are the chinese characters in the last message a single word or are there spaces inbetween?

**Comment by TETYYS** [comment]
No spaces on all three messages.

**Comment by TETYYS** [comment]
I think it's reproducible for whole block (0x20000 to 0x2A6DF) including invalid unicode characters such as \U0002A6D9 (𪛙) (this is affected by this bug more).

**Comment by fourtf** [comment]
Fixed in https://github.com/fourtf/chatterino2/commit/f4cf464ddb54ef0ebdb5eefa5a7cc8aa73ee64a4
