### ISSUE TITLE
User cards from "Viewer list" won't close

### ISSUE THREAD

**Issue by wigoor** [fourtf/chatterino2#759]
The cards from Viewer list can't be closed and will stack with "normal" chat cards.

https://i.imgur.com/lLWzSg3.png

Only way to close is in taskbar menu. https://i.imgur.com/NWkGUa3.png

----

Related issue, hard to find the close button for Viewer list https://i.imgur.com/Lchwj4x.png

c872db3-1

**Comment by TranRed** [comment]
The related issue should be part of #389
