### ISSUE TITLE
Notification while channel is on air

### ISSUE THREAD

**Issue by nNullSpace** [fourtf/chatterino2#788]
Notification while channel is on air

An option to let users know some channel is live.
1. blink the Chatterino item on windows bottom bar, or beep
2. prefix the tab name of a channel with some character, for example: (channel_name) -> 🔘(channel_name)

**Comment by 23rd** [comment]
The notification system is already built into the Chatterino 2. 
You may need to update to the latest nightly version.

![image](https://user-images.githubusercontent.com/4051126/46788407-a8e64900-cd42-11e8-9db9-5bbf8e6658ef.png)

**Comment by nNullSpace** [comment]
Got it and thank you, 23rd.
