### ISSUE TITLE
(suggestion) tab title context menu: copy channel twitch url or channel name

### ISSUE THREAD

**Issue by nNullSpace** [fourtf/chatterino2#789]
Chatterino is a good tool to watch twtich channel chat anonmously, and sometimes users need to open a channel in a browser.
In this case, it might be helpful to copy a channel url in Chatterino and paste in a browser and open.

(or direct open the channel in system default browser from Chatterino? )

**Comment by 23rd** [comment]
> (or direct open the channel in system default browser from Chatterino? )
Maybe you mean this.

![image](https://user-images.githubusercontent.com/4051126/46788058-05953400-cd42-11e8-9814-ae104e4c0e89.png)

**Comment by nNullSpace** [comment]
Got it and thank you again, 23rd.
