### ISSUE TITLE
Refresh emotes with F5

### ISSUE THREAD

**Issue by gempir** [fourtf/chatterino2#804]
It would be really useful to refresh emotes (subs + channel) with a keybinding. Usally refreshing in browsers is F5 so F5 could make sense here aswell.

**Comment by machgo** [comment]
I got it working with a F6, but not with F5
6c30be9a3d4e44b9996c8bd8b73e56a24bb7b85f

F5 seems to be bound by another parent control, so it never triggers my shortcut. Maybe someone with a little more QT-Experience can help me?

**Comment by pajlada** [comment]
it's bound here https://github.com/fourtf/chatterino2/blob/master/src/widgets/Window.cpp#L254
feel free to change that F5 to something else

**Comment by machgo** [comment]
Thanks pajlada, seems I was tired yesterday and didn't saw that.
It's now working - I've created the PR.
