### ISSUE TITLE
Username tab completion inconsistency

### ISSUE THREAD

**Issue by infowolfe** [fourtf/chatterino2#813]
Sometimes users who've recently spoken in a moderately large (but relatively slow) chat (~1000-1500 viewers) are not in the tab completion list accessed via `@abc<tab>`. I'm not quite sure why they're not being added in to the tab complete list, but it's happening pretty regularly. I would recommend a similar methodology to suggested in #14 and/or sorting user tab-complete by who most recently spoke.

**Comment by pajlada** [comment]
Issue has something to do with case-sensitivity and hashing of the completion model, I've looked into it a bit but not committed to fixing it just yet
