### ISSUE TITLE
Problem with Custom Mod Icons

### ISSUE THREAD

**Issue by peacedude** [fourtf/chatterino2#829]
Just downloaded the latest nightly build(v1.0.815) and it seems that I crash every time i try to join a channel with custom mod icons. Tried removing all files in %AppData%\Chatterino2\ but it did not help.

**Comment by TranRed** [comment]
Does work now with ightly v1.0.816 built 2018-10-25T21:27:45.0000000Z

I think this can be closed :) 👍 💯 😂

**Comment by peacedude** [comment]
Yeah, seems like it got fixed.
