### ISSUE TITLE
Holding ctrl and pressing Notepad Enter doesn't save the text in textbox

### ISSUE THREAD

**Issue by Fawcan** [fourtf/chatterino2#832]
Hold ctrl + using "regular" Enter the message is saved in the textbox.
Using the Numpad Enterbutton doesn't save the text in textbox.

**Comment by Ckath** [comment]
it just didnt see the ctrl with `event->modifiers() == Qt::ControlModifier` and numlock enter but does when doing it as stated in some docs through `event->modifiers() & Qt::ControlModifier` eShrug
