### ISSUE TITLE
feature request: links to join / add new split for hosted channels

### ISSUE THREAD

**Issue by Confuseh** [fourtf/chatterino2#837]
i dont wanna press ctrl+r and put in the channel name when with this feature i would be able to just click :slightly_smiling_face: 

![suggestion](https://puu.sh/BRsyQ/ca290e6073.png)

**Comment by apa420** [comment]
Duplicate to some extent of #787

**Comment by fourtf** [comment]
Closing because it's a duplicate of https://github.com/fourtf/chatterino2/issues/787
