### ISSUE TITLE
More parameters in the Moderation buttons

### ISSUE THREAD

**Issue by cineafx** [fourtf/chatterino2#851]
Having additional parameters like {message} or {channel} might be useful for modding.  
An example would be for a !nuke command. Quickly allowing you to timeout spam bots with a certain message.

 - [x] `{message}`
 - [x] `{channel}`

![image](https://user-images.githubusercontent.com/7873738/47746812-31dc0a80-dc87-11e8-81c0-f47962de094d.png)

Channel is useful for example for reports were the syntax includes the channel name in some way.
I can't really think about any other parameters though.

**Comment by TranRed** [comment]
{channel} seems to be already in place by now:

![grafik](https://user-images.githubusercontent.com/16636423/57016291-a5041080-6c19-11e9-9b93-d088d9af47b6.png)
![grafik](https://user-images.githubusercontent.com/16636423/57016387-147a0000-6c1a-11e9-956a-ef9383789999.png)
![grafik](https://user-images.githubusercontent.com/16636423/57016339-e5638e80-6c19-11e9-8a51-01dddf05ee82.png)

**Comment by pajlada** [comment]
Check out the latest nightly, feel free to re-open if things don't work as expected
