### ISSUE TITLE
Move turbo badge from authority to vanity

### ISSUE THREAD

**Issue by gapbl4** [fourtf/chatterino2#852]
![](https://i.imgur.com/MOnAsDb.png)
Turbo and prime are essentially the same since you can switch prime badge to turbo (not sure if it's true these days though).
Anyway, I feel that turbo doesn't belong in authority badges as it doesn't represent any authority.

**Comment by SLCH** [comment]
Having turbo usually indicates person is a streamer.
Agree about it not having authority.
Dont agree about putting it into vanity.

**Comment by gapbl4** [comment]
> Having turbo usually indicates person is a streamer.

When did they make it so it started indicating person as a streamer?
I thought it was a turbo sub/prime only, and streamers have their check mark, no?

**Comment by SLCH** [comment]
> When did they make it so it started indicating person as a streamer?

Other than streamers no one has benefit having turbo anymore.

**Comment by gapbl4** [comment]
Still it's not streamer exclusive feature and is similar to twitch prime

**Comment by pajlada** [comment]
actually everyone can get turbo https://www.twitch.tv/turbo

I don't know of anyone who has turbo, so I can't really try it out but I'd like to see how the badge slots are set up in twitch chat before making any changes to this

**Comment by apa420** [comment]
I'm the one who implemented the feature and used pre-existing groups where: turbo was in the authority group.

**Comment by SLCH** [comment]
> the benefit is ad-free viewing all across Twitch, which is not something you get from Prime anymore

my bad, i remembered it being so for turbo.

**Comment by pajlada** [comment]
fixed
