### ISSUE TITLE
"Pause chat when hovering" option fix has created some problems

### ISSUE THREAD

**Issue by bennyhillthebest** [fourtf/chatterino2#853]
- if the option is selected the chat will keep scrolling even if the user has scrolled up to look at a message (while the right behaviour is still found if the option is not selected)
- if the option is not selected and the user, after scrolling up, selects some text, it will happen that the chat will move up and down while correctly highlighting the text

Thanks a lot for the amazing software.

**Comment by fourtf** [comment]
https://github.com/fourtf/chatterino2/commit/6416bf39275b4da522d9af622753ed697c5daad4
