### ISSUE TITLE
Does client ID really need to be input manually?

### ISSUE THREAD

**Issue by DatGuy1** [fourtf/chatterino2#856]
If chatterino's client id can be changed then ignore and close this, but is there a reason that LogInWithCredentials (and more specifically AdvancedLoginWidget) require a specific field for client ID? Can't it just be `7ue61iz46fz11y3cugd0l3tawb4taal`, or at least default to it?

**Comment by DatGuy1** [comment]
Yes but there's a reason that the advanced tab is there

**Comment by pajlada** [comment]
I don't think the client ID should be pre-filled in with a default value. I could possibly concede with a "copy c2 client id" button but that'd be a separate issue.
