### ISSUE TITLE
error: ‘qsizetype’ does not name a type; did you mean ‘iswctype’?

### ISSUE THREAD

**Issue by Jarel1337** [fourtf/chatterino2#857]
Just tried compiling it on Linux (current master (9ced50e94ed8e40846deef46a7381a0188e59f2a).
Got the following error:

> error: ‘qsizetype’ does not name a type; did you mean ‘iswctype’?

on /src/messages/LimitedQueue.hpp {233,114}

This was on GCC 7.3
QT 5.9.4
haven't tried if reproducible on other installs/machines/OS

**Comment by pajlada** [comment]
Qt 5.10 is required, as specified in the build guide https://github.com/fourtf/chatterino2/blob/master/BUILDING_ON_LINUX.md#linux
