### ISSUE TITLE
TwitchCon Badge not showing in the nightly

### ISSUE THREAD

**Issue by TranRed** [fourtf/chatterino2#858]
Build hash: c11d151

People (ruk0 and arzenhuz) reported it works in beta version

Twitch chat:
![grafik](https://user-images.githubusercontent.com/16636423/47952751-8f68a380-df74-11e8-953a-8ec34fcf2bbc.png)

Chatterino:
![grafik](https://user-images.githubusercontent.com/16636423/47952755-a3aca080-df74-11e8-80ff-2496aac1afb4.png)

My settings:
![grafik](https://user-images.githubusercontent.com/16636423/47952769-ca6ad700-df74-11e8-9724-7c31d9786dd6.png)

**Comment by pajlada** [comment]
Fixed in 90309d00eadf605a32eb6b1c04a9007171204ac2
