### ISSUE TITLE
smol button for the emotes window

### ISSUE THREAD

**Issue by SLCH** [fourtf/chatterino2#873]
Was it intended or bad scaling ?

https://yadi.sk/i/7srjMhxDHKaITA

**Comment by pajlada** [comment]
What scaling are you running at? The button looks fine on my 200% monitor with a ui scale of 2x
![image](https://user-images.githubusercontent.com/962989/48354377-da2f9d00-e691-11e8-8dd2-afcf43a0acbc.png)

btw, you can direct-upload images to github by just copy-pasting them into the same place where you type your text

**Comment by fourtf** [comment]
Works as intended.
