### ISSUE TITLE
VIP support

### ISSUE THREAD

**Issue by TETYYS** [fourtf/chatterino2#875]
- [x] Badges
- [x] Message send intervals

**Comment by notheowner** [comment]
Add support(tab complete) for the new commands like /vip <name>, /vips etc.

From twitch help docs(https://help.twitch.tv/customer/portal/articles/2960705-managing-roles-for-your-channel)
![chrome_2018-11-14_23-56-33](https://user-images.githubusercontent.com/25968992/48520582-0bae9100-e869-11e8-93b5-fbb3812cd606.png)

**Comment by pajlada** [comment]
VIPs aren't added from the chatters list thing atm http://tmi.twitch.tv/group/user/pajlada/chatters

**Comment by pajlada** [comment]
fixed, there's a chance we need to look over what rate limit VIPs **actually** have but that's up to you to tell me when you get disconnected due to crossing the limit
