### ISSUE TITLE
Automod control - allow/deny

### ISSUE THREAD

**Issue by wigoor** [fourtf/chatterino2#887]
Currently not possible to see AutoMod messanges.
![](https://i.imgur.com/GDLcNPy.png)

**Comment by VulpesHD** [comment]
+1 I also want this feature to be added

**Comment by steevel** [comment]
+1 This is the main reason I still need the twitch chat open

**Comment by apa420** [comment]
I've tried implementing it but the documentation on this is lacking, if twitch would update their docs that would be nice
