### ISSUE TITLE
Tab creation size issue

### ISSUE THREAD

**Issue by maith1** [fourtf/chatterino2#890]
When I click the plus button to create a new tab, the window show up in the center of the screen but with two layers of the icons that show up at the top right of windows (- box X) and I can't click on anything within the window unless I click the box icon. When I do that, the windows goes up to the top left of my monitor and one of the layers of icons goes away and I am able to click on selection items in the window.

**Comment by hemirt** [comment]
can you provide a gif/webm/video/series of pictures describing this issue?

**Comment by maith1** [comment]
At the current moment I cannot because of another issue ticket I have opened up about how I cannot open Chatterino 2 because it keeps crashing. Once that is fixed then I will be able to provide a screenshot.

**Comment by hemirt** [comment]
@maith1 https://github.com/fourtf/chatterino2/issues/889#issuecomment-443462696

**Comment by pajlada** [comment]
I think this has been fixed in the latest nightly. if it hasn't, please open a new issue
