### ISSUE TITLE
Window size issue on startup

### ISSUE THREAD

**Issue by maith1** [fourtf/chatterino2#891]
When Chatterino is started up after being closed entirely, it's window size is slightly larger than it was when it was closed, not allowing me to be able to move or resize the window as the top bar is outside the monitor.

**Comment by TranRed** [comment]
In my opinion this was fixed already and does not occur anymore on nightly. CBA to find the related issue rn sonde I'm not at home

**Comment by pajlada** [comment]
please open a new issue if this still occurs in the latest nightly build (available under github releases)
