### ISSUE TITLE
font smoothness and suggestions

### ISSUE THREAD

**Issue by Dolev24** [fourtf/chatterino2#893]
why is the font isnt the same as chatterino 1? i tried tons of options and all of them are kinda pixelated.
https://gyazo.com/69b87ba9ecbfba08869a06df4821533c
- also i just wanna request the names to be like the chatterino 1 and be bold.
- also can we have the same color as chatterino 1 as an option?

**Comment by gapbl4** [comment]
You can try nightly build, names are bold there.

**Comment by Dolev24** [comment]
> You can try nightly build, names are bold there.

cant find it

**Comment by Defman21** [comment]
https://github.com/fourtf/chatterino2/releases/tag/nightly-win

**Comment by Dolev24** [comment]
for some reason my chatterino crashes when i check this option

**Comment by JAYR4GE** [comment]
same - as soon as i click that checkbox it crashes

**Comment by pajlada** [comment]
that checkbox doesn't crash on nightly anymore. please open a new issue if this issue still bothers you even with that setting. thanks!
