### ISSUE TITLE
Cannot open Chatterino

### ISSUE THREAD

**Issue by DuskDarker** [fourtf/chatterino2#909]
"Chatterino cannot be opened because of a problem."

**Comment by TranRed** [comment]
- What version are you using?
- Did you try resetting (i.e. deleting) setting/commands/layouts to check if one of these is corrupt?
- Did you try reinstalling?

**Comment by apa420** [comment]
Did you download VC++ 2017 as described here?
https://github.com/fourtf/chatterino2/blob/master/README.md#downloading

**Comment by pajlada** [comment]
Closed due to inactivity. If you still have this issue, feel free to open a new issue (make sure to answer the questions from TranRed and apa420 in that issue).
