### ISSUE TITLE
Double click a username in chat to reply to him in chat

### ISSUE THREAD

**Issue by OlemcDEV** [fourtf/chatterino2#919]
Make it so you can double click a user in chat to reply.

Scenario:
Double click Arnold
Make chat enter "@Arnold, "type stuff here""

**Comment by 23rd** [comment]
You can use right click.

**Comment by pajlada** [comment]
each method described here so far works, but the one mentioned by 23rd is the one closest to your feature request. so I will assume this already satisfies your needs. if not, please feel free to open another issue describing what's lacking in the right-click feature.

**Comment by OlemcDEV** [comment]
Ah, sorry. My lack of knowledge.
