### ISSUE TITLE
timed out messages are displayed similar to highlight colour

### ISSUE THREAD

**Issue by TranRed** [fourtf/chatterino2#932]
Looks a bit confusing to me. It looks like you were pinged in this message on first glance. 

![grafik](https://user-images.githubusercontent.com/16636423/51786599-cfe84f80-2166-11e9-9b4d-0108f6b807ab.png)

**Comment by Evanito** [comment]
What does a timed out mention that *does* mention you look like?

**Comment by TranRed** [comment]
excellent question! Didn't think about that one yet. 
Answer is: Looks like something in between a mention and a timed out message, that does not mention you. Looks distinguishable on the screenshot, but I feel it's too close in chat.  Maybe it's just my impression and custom themes will fix it for me, once they are available.

![grafik](https://user-images.githubusercontent.com/16636423/51890021-4a011a00-239b-11e9-9a2b-0b68f6b20f0a.png)

Old style for comparison:
![grafik](https://user-images.githubusercontent.com/16636423/51890497-808b6480-239c-11e9-8617-2262d2ca209f.png)

**Comment by Evanito** [comment]
What if instead of the striped red background, it was a light grey

**Comment by TranRed** [comment]
sounds good to me

**Comment by Evanito** [comment]
Recent commit by @apa420 allows toggling of highlighting removed messages, instead only grays out like old style.

**Comment by TranRed** [comment]
nice work :)
