### ISSUE TITLE
Service messages are barely visible in light and white themes

### ISSUE THREAD

**Issue by CaptainFlint** [fourtf/chatterino2#938]
The messages about connecting are unreadable for non-dark themes:

![image](https://user-images.githubusercontent.com/6475044/52065746-36ff6d00-2588-11e9-9b06-20c75ad54e7a.png)

Nightly v1.0.876 built 2019-01-31T07:32:25.0000000Z

**Comment by pajlada** [comment]
Hey, the message should be readable now in the latest nightly version.
