### ISSUE TITLE
[ISSUE] Pop-up windows take up the same size as Chatterino size.

### ISSUE THREAD

**Issue by BrianVEA** [fourtf/chatterino2#946]
Good day, I'm sorry if this issue was already reported in the past, I've attempted to search through the reported issues but were unable to find any similar to what I'm experiencing.

When ever I, for example click on someones username when I am using chatterino, rather than the window popping up in appropriate size, the pop-up window is the same size as my chatterino window, causing it to look as following.

![discord_ 2019-02-03 20_37_32](https://user-images.githubusercontent.com/21298477/52181562-8dbcaf00-27f3-11e9-965d-16408c5554ad.png)

It overlaps the whole chatterino window, making it unable for me to see the chat, and it is also annoying to close said window as I am unable to change it in size, or close it, so I have to move it, then click on Chatterino once more to go back to the chat.

I hope this is enough information, will do my best to reply to any messages left on here.

Yours sincerely,

Brian

**Comment by apa420** [comment]
Did you compile your chatterino by yourself?
If so, did you check the requirements of qt being 5.10 or later?
There have been some similar issues to this because of older qt version.

**Comment by apa420** [comment]
Might also help to give some information on what version of chatterino, how you got it and what OS you are on

**Comment by BrianVEA** [comment]
Hi, apologies I wrote a message before with the version and OS but I had to restart my browser and thus, the information got lost.

I am currently operating windows 10, 64 bit, Chatterino Version 2.0.4.

I did not compile Chatterino myself, I used the exe installer.

**Comment by BrianVEA** [comment]
I have managed to resolve this issue, it was caused by my displayfusion, which was set to resize the Chatterino window once it was ran, it how ever did this every time a chatterino window was opened, resizing those. The fix for this was to edit the process to only do it once per process-name, sorry for posting a bug report here for something I caused myself, have a wonderful day!
