### ISSUE TITLE
Missing package when building Chatterino in Debian/Ubuntu

### ISSUE THREAD

**Issue by bennyhillthebest** [fourtf/chatterino2#957]
I have just build Chatterino in Debian and i found that libboost-filesystem1.67-dev is needed. I would add in the building guide for Ubuntu/Debian the libboost-all-dev package so it will continue to work even when boost is updated with an increased number version.

**Comment by pajlada** [comment]
Fixed in #1069  - documentation has been updated in the nightly branch
Thanks!
