### ISSUE TITLE
FeelsGoodMan

### ISSUE THREAD

**Issue by coral** [fourtf/chatterino2#959]
FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan FeelsGoodMan

**Comment by pajlada** [comment]
Please stop spamming the repository
