### ISSUE TITLE
lots of gray names?

### ISSUE THREAD

**Issue by Tyr808** [fourtf/chatterino2#960]
Hey, loving chatterino so far, but is this a bug or have I done something wrong?  half of my users names are all identical shades of gray 

https://imgur.com/Krycfii

**Comment by gapbl4** [comment]
That's just people who never set custom color, good indication for lots of new users in chat.
In browser it will just show some random default color, so you never notice it.

**Comment by apa420** [comment]
Chatterino will also color names differently because they might otherwise be hard to see

**Comment by Tyr808** [comment]
> Chatterino will also color names differently because they might otherwise be hard to see

Sorry, what do you mean by this, am I missing an option somewhere or is this a planned feature not yet implemented?  I get why the names aren't colored because many haven't set a color yet, but it would be great if it did what default Twitch chat does for readability and to quickly see a name at a glance.  The contrast of the gray name color on the dark theme is hard to read currently.

**Comment by pajlada** [comment]
What gapbl4 stated is correct, users who have not set a color are just gray in Chatterino, whereas in web chat they receive a random color for each session.

We could possibly assign a color based on the users ID, but that should go in another issue. Let me know if you have any other questions.
