### ISSUE TITLE
Restarted computer and all channels are gone

### ISSUE THREAD

**Issue by Quantummmm** [fourtf/chatterino2#961]
I restarted my computer without closing Chatterino, the next launch it said "Chatterino did not close correctly" Then I pressed "Okay". Once the application loaded up, all of my channels were gone. It only showed two "empty" channels.

**Comment by Dolev24** [comment]
happened to me too, from now on i have backups of the appdata

**Comment by pajlada** [comment]
issue with saving the window layout file, currently being worked on by @TranRed in #1039

**Comment by pajlada** [comment]
@Quantummmm this has been fixed in the latest nightly version, available from github releases. please try that out and let us know if you still have this issue
