### ISSUE TITLE
Nightly is borked

### ISSUE THREAD

**Issue by Evanito** [fourtf/chatterino2#973]
As a regular user of every nightly:

Image: https://cdn.discordapp.com/attachments/535790601308733460/553732228215996416/unknown.png

- Cannot chat, enter just adds newline
- Cannot view chats, they change to the other channel but never join
- Ignores user's window-layout and shows above every time

I am using the portable functionality.

**Comment by gapbl4** [comment]
Same issue here, me in tears ![](https://i.imgur.com/F2GEv8r.png)

**Comment by holysnipz** [comment]
PepeHands

Seems like only way is [downgraded to commit ca14a76b](https://ci.appveyor.com/project/pajlada/chatterino2/builds/22871405/artifacts)

**Comment by pajlada** [comment]
I have updated appveyor to not push new builds to the release until refactor is done, and I have updated the release manually with the working chatterino2.zip file
