### ISSUE TITLE
Broken builds on linux since 87e9066

### ISSUE THREAD

**Issue by alice-lilith** [fourtf/chatterino2#974]
Every commit since [this commit](https://github.com/fourtf/chatterino2/commit/87e9066d6ffc445c6371c44a723dd390ce5dd328) fails to build, with the [following error](https://pastebin.com/vPjTs24j)
OS: Manjaro Linux 4.20.12
This build fails the same way whether it's from the AUR script or done manually,
```
git submodule update --init --recursive
mkdir build && cd build
qmake ..
make -j12
```
(this is essentially identical to the [aur script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chatterino2-git))
The older commits still build fine, so I'm guessing it's that specific reorganization that breaks it.

**Comment by pajlada** [comment]
Chatterino2 is currently in "refactor mode" - latest build you should be building if you're interested in running the app is 3f41dfeff942d9becb311a4b1769e8445da016af - will see if I can update the README to reflect this
