### ISSUE TITLE
Filter out certain channels from your /mentions

### ISSUE THREAD

**Issue by Trizze** [fourtf/chatterino2#98]
I want to be able to have a /mentions channel with mentions of my name but filter out my own stream for example. Because otherwise my stream is going to overflow the /mentions channel because most people tag me while I stream. Then I don't see mentions from other channels during the time I am streaming.

**Comment by Trizze** [comment]
Also perhaps blacklist people from your /mentions perhaps? I'm thinking about bots etc that spam your name, you don't really care about what they say anyway.

**Comment by TranRed** [comment]
@Trizze second feature already exists 

example:
![chatterino_2017-08-17_18-58-25](https://user-images.githubusercontent.com/16636423/29424003-29a9cbd0-837e-11e7-8b93-ba72c08eb2ec.png)
