### ISSUE TITLE
Option to make double clicking channel name open the stream in web browser

### ISSUE THREAD

**Issue by Karabast** [fourtf/chatterino2#984]
![Channel name](https://i.imgur.com/vv5gX0l.png)

Add an option to make double clicking the channel name open the stream in web browser.

**Comment by Ckath** [comment]
what would make sense here? an option to give this functionality instead of the default one(change channel) or move either this or that to another combo like double click rmb

**Comment by apa420** [comment]
You can already open the stream from chatterino
![](https://i.nuuls.com/4M-tV.png)

**Comment by pajlada** [comment]
I think the current functionality makes sense already (changing channel). and as apa420 stated, just clicking the hamburger icon gives you the option to open the stream in all kinds of ways, which I think is good enough. 

I could possibly see the hamburger menu opening when right-clicking anywhere in the header, but that's a separate issue.
