### ISSUE TITLE
Adjust this setting description

### ISSUE THREAD

**Issue by 161134050** [fourtf/chatterino2#986]
I feel like this option should say "Separate chat messages with lines" or at least "Separate messages with lines", I feel like its currently a little ambigious for a new user

![image](https://user-images.githubusercontent.com/39843740/55076720-19a2d700-50d1-11e9-8cb9-92dffd0c63b5.png)

**Comment by Ckath** [comment]
its already under Messages: though, and it live updates

**Comment by 161134050** [comment]
true
