### ISSUE TITLE
Disable requests to braize.pajlada.com when link hovering info is disabled

### ISSUE THREAD

**Issue by 161134050** [fourtf/chatterino2#988]
I currently have this option unselected:
![image](https://user-images.githubusercontent.com/39843740/55164506-bbe0be80-51a6-11e9-9dc7-fd2220b42f33.png)

However, requests to braize.pajlada.com/chatterino/link_resolver/ are still being made.

Pls fix Volvo

**Comment by hemirt** [comment]
close

**Comment by hemirt** [comment]
close @pajlada

**Comment by pajlada** [comment]
fixed in nightly
